// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {subtitleparser} from '../models';

export function AddCollectionVideo(arg1:number,arg2:number):Promise<void>;

export function AddCollectionVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function AddDirectory(arg1:string,arg2:string):Promise<models.ScanDirectory>;

export function AddPersonVideo(arg1:number,arg2:number):Promise<void>;

export function AddPersonVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function AddTagToVideo(arg1:number,arg2:number):Promise<void>;

export function AddVideo(arg1:string):Promise<models.Video>;

export function ApplyLocalMetadata(arg1:services.LocalMetadataApplyRequest):Promise<services.LocalMetadataApplyResult>;

export function ApplyLocalMetadataBatch(arg1:services.LocalMetadataBatchApplyRequest):Promise<services.LocalMetadataBatchResult>;

export function ApproveAITagCandidate(arg1:number):Promise<services.AITaggingReviewItem>;

export function BatchAddTagToVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function BatchDeleteVideos(arg1:Array<number>,arg2:boolean):Promise<services.BatchVideoOperationResult>;

export function BatchMoveVideos(arg1:Array<number>,arg2:string):Promise<services.BatchVideoOperationResult>;

export function BatchRefreshVideoMetadata(arg1:Array<number>):Promise<services.BatchVideoOperationResult>;

export function BatchRemoveTagFromVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function CancelLocalMetadataBackfill():Promise<void>;

export function CancelSubtitle():Promise<void>;

export function CancelSubtitleTask(arg1:number):Promise<void>;

export function CancelTechnicalBackfill():Promise<void>;

export function CheckSubtitleDependencies():Promise<Record<string, boolean>>;

export function CreateCollection(arg1:string,arg2:string):Promise<models.MediaCollection>;

export function CreatePerson(arg1:string,arg2:string):Promise<models.Person>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteDirectory(arg1:number):Promise<void>;

export function DeleteSavedLibraryView(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteVideo(arg1:number,arg2:boolean):Promise<void>;

export function DownloadSubtitleDependencies():Promise<void>;

export function ForceGenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function GenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function GetAIQualityReport(arg1:services.AIQualityFilter):Promise<services.AIQualityReport>;

export function GetAITagLibrary():Promise<Array<models.Tag>>;

export function GetAITaggingStatusSummary():Promise<services.AITaggingStatusSummary>;

export function GetAllDirectories():Promise<Array<models.ScanDirectory>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetAllVideos():Promise<Array<models.Video>>;

export function GetCleanupCandidates(arg1:number,arg2:number,arg3:number):Promise<services.CleanupAnalysis>;

export function GetCleanupStatus():Promise<services.CleanupStatus>;

export function GetCollectionDetail(arg1:number):Promise<services.CollectionDetail>;

export function GetLibrarySubtitleHits(arg1:string,arg2:Array<number>):Promise<Array<services.LibrarySubtitleHit>>;

export function GetLibraryWatcherStatus():Promise<services.LibraryWatcherStatus>;

export function GetLocalMetadataBackfillStatus():Promise<services.LocalMetadataBackfillStatus>;

export function GetLocalMetadataDiff(arg1:number):Promise<services.LocalMetadataDiff>;

export function GetPersonDetail(arg1:number,arg2:number,arg3:number):Promise<services.PersonDetail>;

export function GetPreviewSession(arg1:number):Promise<services.PreviewSession>;

export function GetSettings():Promise<models.Settings>;

export function GetShortFeedServerStatus():Promise<services.ShortFeedServerStatus>;

export function GetStartupError():Promise<string>;

export function GetSubtitleEditDocument(arg1:number):Promise<services.SubtitleEditDocument>;

export function GetSubtitleEngineStatuses():Promise<Array<services.SubtitleEngineStatus>>;

export function GetSubtitleQueueState():Promise<services.SubtitleQueueSnapshot>;

export function GetSubtitleSegments(arg1:number):Promise<Array<subtitleparser.Segment>>;

export function GetTechnicalBackfillStatus():Promise<services.TechnicalBackfillStatus>;

export function GetVideoDetails(arg1:number):Promise<services.VideoDetails>;

export function GetVideosByDirectory(arg1:string):Promise<Array<models.Video>>;

export function GetVideosPaginated(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<models.Video>>;

export function ListAITagCandidates(arg1:number,arg2:string,arg3:string):Promise<Array<services.AITaggingReviewItem>>;

export function ListCollections(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<services.CollectionListItem>>;

export function ListPeople(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<services.PersonListItem>>;

export function ListRecentlyPlayed(arg1:number):Promise<Array<models.Video>>;

export function ListRecentlyPlayedWithFilter(arg1:services.LibraryFilter,arg2:string,arg3:number,arg4:number):Promise<Array<models.Video>>;

export function ListSameSourceRelations(arg1:string,arg2:boolean):Promise<Array<services.VideoSameSourceReviewItem>>;

export function ListSavedLibraryViews():Promise<Array<models.SavedLibraryView>>;

export function ListTrashEntries():Promise<Array<models.VideoTrashEntry>>;

export function LogFrontend(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MarkSameSourceRelationRead(arg1:number):Promise<void>;

export function MergeTags(arg1:Array<number>,arg2:number):Promise<services.MergeTagsResult>;

export function MoveDirectory(arg1:string,arg2:string):Promise<services.FolderMigrationResult>;

export function MoveVideo(arg1:number,arg2:string):Promise<services.FileMigrationResult>;

export function OpenDirectory(arg1:number):Promise<void>;

export function PlayRandomVideo():Promise<services.PlaybackAttemptResult>;

export function PlayRandomVideoWithFilter(arg1:services.RandomPlayRequest):Promise<services.PlaybackAttemptResult>;

export function PlayVideo(arg1:number):Promise<services.PlaybackAttemptResult>;

export function PrepareSubtitleEngine(arg1:services.SubtitleEngine):Promise<void>;

export function PreviewExternally(arg1:number):Promise<void>;

export function PreviewLocalMetadataBatch(arg1:Array<number>):Promise<services.LocalMetadataBatchPreview>;

export function RefreshVideoMetadata(arg1:number):Promise<void>;

export function RefreshVideoTechnicalMetadata(arg1:number):Promise<services.VideoDetails>;

export function RejectAITagCandidate(arg1:number):Promise<void>;

export function RejectAITagCandidatesByVideo(arg1:number):Promise<number>;

export function RejectSameSourceRelation(arg1:number):Promise<void>;

export function RelocateVideo(arg1:number,arg2:string):Promise<void>;

export function RemoveCollectionCover(arg1:number):Promise<void>;

export function RemoveCollectionVideo(arg1:number,arg2:number):Promise<void>;

export function RemovePersonAvatar(arg1:number):Promise<void>;

export function RemovePersonVideo(arg1:number,arg2:number):Promise<boolean>;

export function RemoveTagFromVideo(arg1:number,arg2:number):Promise<void>;

export function RenameVideo(arg1:number,arg2:string):Promise<void>;

export function ReorderCollectionVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function ResolveVideoArtwork(arg1:number,arg2:string):Promise<services.VideoArtworkData>;

export function RestoreTrashEntry(arg1:number):Promise<models.Video>;

export function RetranslateSubtitleEntries(arg1:services.SubtitleRetranslateRequest):Promise<services.SubtitleRetranslateResult>;

export function RetryAITagging(arg1:number):Promise<void>;

export function RetryLibraryWatcherRoot(arg1:number):Promise<services.LibraryWatchRootStatus>;

export function SaveAITagLibrary(arg1:Array<services.AITagLibraryInput>):Promise<Array<models.Tag>>;

export function SaveLibraryView(arg1:services.SavedLibraryViewInput):Promise<models.SavedLibraryView>;

export function SaveSubtitleEditDocument(arg1:services.SubtitleSaveRequest):Promise<services.SubtitleSaveResult>;

export function ScanDirectory(arg1:string):Promise<Array<string>>;

export function ScanDirectoryWithInfo(arg1:string):Promise<Array<services.ScannedFile>>;

export function SearchLibraryVideoPage(arg1:services.LibraryVideoPageRequest):Promise<services.LibraryVideoPage>;

export function SearchLibraryVideos(arg1:services.LibraryFilter,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchSubtitleMatches(arg1:string,arg2:number):Promise<Array<services.SubtitleSearchMatch>>;

export function SearchSubtitleMatchesWithFilters(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number):Promise<Array<services.SubtitleSearchMatch>>;

export function SearchVideos(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosByTags(arg1:Array<number>,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosWithFilters(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number,arg10:number):Promise<Array<models.Video>>;

export function SelectCollectionCover():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectMigrationDestinationDirectory():Promise<string>;

export function SelectMigrationSourceDirectory():Promise<string>;

export function SelectPersonAvatar():Promise<string>;

export function SetCollectionCover(arg1:number,arg2:string):Promise<models.MediaCollection>;

export function SetPersonAvatar(arg1:number,arg2:string):Promise<models.Person>;

export function SetVideoFavorite(arg1:number,arg2:boolean):Promise<models.Video>;

export function SetVideoWatched(arg1:number,arg2:boolean):Promise<models.Video>;

export function StartCleanupAnalysis(arg1:number,arg2:number,arg3:number):Promise<services.CleanupStatus>;

export function StartLocalMetadataBackfill():Promise<services.LocalMetadataBackfillStatus>;

export function StartTechnicalBackfill():Promise<services.TechnicalBackfillStatus>;

export function SyncScanDirectories():Promise<services.ScanSyncResult>;

export function TriggerAITagging():Promise<boolean>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<models.MediaCollection>;

export function UpdateDirectory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdatePerson(arg1:number,arg2:string,arg3:string):Promise<models.Person>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateVideoDetails(arg1:services.VideoDetailsUpdate):Promise<services.VideoDetails>;

export function UpdateVideoWatchProgress(arg1:number,arg2:number,arg3:boolean):Promise<models.Video>;

export function ValidateSubtitleEditDocument(arg1:services.SubtitleSaveRequest):Promise<services.SubtitleValidationResult>;
