// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionVideo'](arg1, arg2);
}

export function AddDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2);
}

export function AddTagToVideo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToVideo'](arg1, arg2);
}

export function AddVideo(arg1) {
  return window['go']['main']['App']['AddVideo'](arg1);
}

export function ApproveAITagCandidate(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidate'](arg1);
}

export function BatchAddTagToVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToVideos'](arg1, arg2);
}

export function BatchDeleteVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteVideos'](arg1, arg2);
}

export function BatchMoveVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchMoveVideos'](arg1, arg2);
}

export function BatchRefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['BatchRefreshVideoMetadata'](arg1);
}

export function BatchRemoveTagFromVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromVideos'](arg1, arg2);
}

export function CancelSubtitle() {
  return window['go']['main']['App']['CancelSubtitle']();
}

export function CancelSubtitleTask(arg1) {
  return window['go']['main']['App']['CancelSubtitleTask'](arg1);
}

export function CancelTechnicalBackfill() {
  return window['go']['main']['App']['CancelTechnicalBackfill']();
}

export function CheckSubtitleDependencies() {
  return window['go']['main']['App']['CheckSubtitleDependencies']();
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreatePerson(arg1, arg2) {
  return window['go']['main']['App']['CreatePerson'](arg1, arg2);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteSavedLibraryView(arg1) {
  return window['go']['main']['App']['DeleteSavedLibraryView'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteVideo(arg1, arg2) {
  return window['go']['main']['App']['DeleteVideo'](arg1, arg2);
}

export function DownloadSubtitleDependencies() {
  return window['go']['main']['App']['DownloadSubtitleDependencies']();
}

export function ForceGenerateSubtitle(arg1) {
  return window['go']['main']['App']['ForceGenerateSubtitle'](arg1);
}

export function GenerateSubtitle(arg1) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1);
}

export function GetAITagLibrary() {
  return window['go']['main']['App']['GetAITagLibrary']();
}

export function GetAITaggingStatusSummary() {
  return window['go']['main']['App']['GetAITaggingStatusSummary']();
}

export function GetAllDirectories() {
  return window['go']['main']['App']['GetAllDirectories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllVideos() {
  return window['go']['main']['App']['GetAllVideos']();
}

export function GetCleanupCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCleanupCandidates'](arg1, arg2, arg3);
}

export function GetCleanupStatus() {
  return window['go']['main']['App']['GetCleanupStatus']();
}

export function GetCollectionDetail(arg1) {
  return window['go']['main']['App']['GetCollectionDetail'](arg1);
}

export function GetLibrarySubtitleHits(arg1, arg2) {
  return window['go']['main']['App']['GetLibrarySubtitleHits'](arg1, arg2);
}

export function GetPersonDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPersonDetail'](arg1, arg2, arg3);
}

export function GetPreviewSession(arg1) {
  return window['go']['main']['App']['GetPreviewSession'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShortFeedServerStatus() {
  return window['go']['main']['App']['GetShortFeedServerStatus']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetSubtitleEngineStatuses() {
  return window['go']['main']['App']['GetSubtitleEngineStatuses']();
}

export function GetSubtitleQueueState() {
  return window['go']['main']['App']['GetSubtitleQueueState']();
}

export function GetSubtitleSegments(arg1) {
  return window['go']['main']['App']['GetSubtitleSegments'](arg1);
}

export function GetTechnicalBackfillStatus() {
  return window['go']['main']['App']['GetTechnicalBackfillStatus']();
}

export function GetVideoDetails(arg1) {
  return window['go']['main']['App']['GetVideoDetails'](arg1);
}

export function GetVideosByDirectory(arg1) {
  return window['go']['main']['App']['GetVideosByDirectory'](arg1);
}

export function GetVideosPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVideosPaginated'](arg1, arg2, arg3, arg4);
}

export function ListAITagCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAITagCandidates'](arg1, arg2, arg3);
}

export function ListCollections(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListCollections'](arg1, arg2, arg3, arg4);
}

export function ListPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPeople'](arg1, arg2, arg3, arg4);
}

export function ListRecentlyPlayed(arg1) {
  return window['go']['main']['App']['ListRecentlyPlayed'](arg1);
}

export function ListRecentlyPlayedWithFilter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRecentlyPlayedWithFilter'](arg1, arg2, arg3, arg4);
}

export function ListSameSourceRelations(arg1, arg2) {
  return window['go']['main']['App']['ListSameSourceRelations'](arg1, arg2);
}

export function ListSavedLibraryViews() {
  return window['go']['main']['App']['ListSavedLibraryViews']();
}

export function ListTrashEntries() {
  return window['go']['main']['App']['ListTrashEntries']();
}

export function LogFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3);
}

export function MarkSameSourceRelationRead(arg1) {
  return window['go']['main']['App']['MarkSameSourceRelationRead'](arg1);
}

export function MergeTags(arg1, arg2) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2);
}

export function MoveDirectory(arg1, arg2) {
  return window['go']['main']['App']['MoveDirectory'](arg1, arg2);
}

export function MoveVideo(arg1, arg2) {
  return window['go']['main']['App']['MoveVideo'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function PlayRandomVideo() {
  return window['go']['main']['App']['PlayRandomVideo']();
}

export function PlayRandomVideoWithFilter(arg1) {
  return window['go']['main']['App']['PlayRandomVideoWithFilter'](arg1);
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function PrepareSubtitleEngine(arg1) {
  return window['go']['main']['App']['PrepareSubtitleEngine'](arg1);
}

export function PreviewExternally(arg1) {
  return window['go']['main']['App']['PreviewExternally'](arg1);
}

export function RefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoMetadata'](arg1);
}

export function RefreshVideoTechnicalMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoTechnicalMetadata'](arg1);
}

export function RejectAITagCandidate(arg1) {
  return window['go']['main']['App']['RejectAITagCandidate'](arg1);
}

export function RejectAITagCandidatesByVideo(arg1) {
  return window['go']['main']['App']['RejectAITagCandidatesByVideo'](arg1);
}

export function RejectSameSourceRelation(arg1) {
  return window['go']['main']['App']['RejectSameSourceRelation'](arg1);
}

export function RelocateVideo(arg1, arg2) {
  return window['go']['main']['App']['RelocateVideo'](arg1, arg2);
}

export function RemoveCollectionCover(arg1) {
  return window['go']['main']['App']['RemoveCollectionCover'](arg1);
}

export function RemoveCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveCollectionVideo'](arg1, arg2);
}

export function RemovePersonAvatar(arg1) {
  return window['go']['main']['App']['RemovePersonAvatar'](arg1);
}

export function RemoveTagFromVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromVideo'](arg1, arg2);
}

export function RenameVideo(arg1, arg2) {
  return window['go']['main']['App']['RenameVideo'](arg1, arg2);
}

export function ReorderCollectionVideos(arg1, arg2) {
  return window['go']['main']['App']['ReorderCollectionVideos'](arg1, arg2);
}

export function RestoreTrashEntry(arg1) {
  return window['go']['main']['App']['RestoreTrashEntry'](arg1);
}

export function RetryAITagging(arg1) {
  return window['go']['main']['App']['RetryAITagging'](arg1);
}

export function SaveAITagLibrary(arg1) {
  return window['go']['main']['App']['SaveAITagLibrary'](arg1);
}

export function SaveLibraryView(arg1) {
  return window['go']['main']['App']['SaveLibraryView'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function ScanDirectoryWithInfo(arg1) {
  return window['go']['main']['App']['ScanDirectoryWithInfo'](arg1);
}

export function SearchLibraryVideoPage(arg1) {
  return window['go']['main']['App']['SearchLibraryVideoPage'](arg1);
}

export function SearchLibraryVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchLibraryVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchSubtitleMatches(arg1, arg2) {
  return window['go']['main']['App']['SearchSubtitleMatches'](arg1, arg2);
}

export function SearchSubtitleMatchesWithFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SearchSubtitleMatchesWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SearchVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosByTags(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideosByTags'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosWithFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SearchVideosWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SelectCollectionCover() {
  return window['go']['main']['App']['SelectCollectionCover']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMigrationDestinationDirectory() {
  return window['go']['main']['App']['SelectMigrationDestinationDirectory']();
}

export function SelectMigrationSourceDirectory() {
  return window['go']['main']['App']['SelectMigrationSourceDirectory']();
}

export function SelectPersonAvatar() {
  return window['go']['main']['App']['SelectPersonAvatar']();
}

export function SetCollectionCover(arg1, arg2) {
  return window['go']['main']['App']['SetCollectionCover'](arg1, arg2);
}

export function SetPersonAvatar(arg1, arg2) {
  return window['go']['main']['App']['SetPersonAvatar'](arg1, arg2);
}

export function SetVideoFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetVideoFavorite'](arg1, arg2);
}

export function SetVideoWatched(arg1, arg2) {
  return window['go']['main']['App']['SetVideoWatched'](arg1, arg2);
}

export function StartCleanupAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCleanupAnalysis'](arg1, arg2, arg3);
}

export function StartTechnicalBackfill() {
  return window['go']['main']['App']['StartTechnicalBackfill']();
}

export function SyncScanDirectories() {
  return window['go']['main']['App']['SyncScanDirectories']();
}

export function TriggerAITagging() {
  return window['go']['main']['App']['TriggerAITagging']();
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDirectory'](arg1, arg2, arg3);
}

export function UpdatePerson(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePerson'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}

export function UpdateVideoDetails(arg1) {
  return window['go']['main']['App']['UpdateVideoDetails'](arg1);
}

export function UpdateVideoWatchProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVideoWatchProgress'](arg1, arg2, arg3);
}
