// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';
import {subtitleparser} from '../models';

export function AddCollectionVideo(arg1:number,arg2:number):Promise<void>;

export function AddCollectionVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function AddDirectory(arg1:string,arg2:string):Promise<models.ScanDirectory>;

export function AddDownloadDirectoryToScan(arg1:string):Promise<services.BrowserDownloadActionResult>;

export function AddImageDirectory(arg1:string,arg2:string):Promise<models.ImageDirectory>;

export function AddPersonImages(arg1:number,arg2:Array<number>):Promise<void>;

export function AddPersonVideo(arg1:number,arg2:number):Promise<void>;

export function AddPersonVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function AddTagToImage(arg1:number,arg2:number):Promise<void>;

export function AddTagToVideo(arg1:number,arg2:number):Promise<void>;

export function AddVersionMembers(arg1:number,arg2:number,arg3:Array<number>):Promise<services.VersionGroupDetail>;

export function AnalyzeEditProject(arg1:services.EditAnalyzeRequest):Promise<services.EditProjectView>;

export function ApplyLocalMetadataBatch(arg1:services.LocalMetadataBatchApplyRequest):Promise<services.LocalMetadataBatchResult>;

export function ApplyWatchlistCandidate(arg1:number,arg2:string):Promise<void>;

export function ApproveAITagCandidate(arg1:number):Promise<services.AITaggingReviewItem>;

export function ApproveImageAITagCandidate(arg1:number):Promise<services.ImageAITaggingReviewItem>;

export function BatchAddTagToImages(arg1:Array<number>,arg2:number):Promise<services.BatchImageOperationResult>;

export function BatchAddTagToVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function BatchCreatePlaybackProxies(arg1:Array<number>):Promise<services.PlaybackProxyStatus>;

export function BatchCreatePlaybackProxiesForFilter(arg1:services.LibraryFilter):Promise<services.PlaybackProxyStatus>;

export function BatchMoveVideos(arg1:Array<number>,arg2:string):Promise<services.BatchVideoOperationResult>;

export function BatchRemoveTagFromVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function CancelAIReviewApproval(arg1:string,arg2:string):Promise<void>;

export function CancelBatchDelete(arg1:string):Promise<boolean>;

export function CancelBrowserDownloadTask(arg1:string):Promise<void>;

export function CancelCleanupAnalysis():Promise<void>;

export function CancelCleanupConsolidation():Promise<void>;

export function CancelCollectionSuggestionAnalysis():Promise<void>;

export function CancelEditAnalysis(arg1:number):Promise<void>;

export function CancelEditProject(arg1:number):Promise<void>;

export function CancelEnhancementModelDownload():Promise<services.EnhancementModelStatus>;

export function CancelEnhancementTask(arg1:number):Promise<void>;

export function CancelFaceAnalysis():Promise<void>;

export function CancelFaceRuntimePrepare():Promise<void>;

export function CancelFrameHashBackfill():Promise<void>;

export function CancelImageAITagging():Promise<void>;

export function CancelImageCleanupAnalysis():Promise<void>;

export function CancelImageEXIFBackfill():Promise<void>;

export function CancelImagePerceptualHashBackfill():Promise<void>;

export function CancelImageSemanticIndex():Promise<void>;

export function CancelLocalMetadataBackfill():Promise<void>;

export function CancelLocalMetadataExport():Promise<void>;

export function CancelMovieChartRefresh():Promise<void>;

export function CancelPerceptualHashBackfill():Promise<void>;

export function CancelPlaybackProxyTask():Promise<void>;

export function CancelSceneIndex():Promise<void>;

export function CancelSceneRuntimePrepare():Promise<void>;

export function CancelSemanticIndex():Promise<void>;

export function CancelSubtitle():Promise<void>;

export function CancelSubtitleEnginePreparation():Promise<void>;

export function CancelSubtitleTask(arg1:number):Promise<void>;

export function CancelSubtitleTranslation(arg1:number):Promise<void>;

export function CancelTechnicalBackfill():Promise<void>;

export function CheckMoveTarget(arg1:string):Promise<services.MoveTargetCheck>;

export function ClearFaceData():Promise<services.FaceDataUsage>;

export function ClearMigrationTarget(arg1:string,arg2:string):Promise<services.DatabaseTargetClearResult>;

export function ClearMovieChartMark(arg1:string):Promise<void>;

export function ClearPlaybackProxies():Promise<services.PlaybackProxyUsage>;

export function ClearShortFeedPIN():Promise<void>;

export function ClearStaleSceneIndex():Promise<services.SceneIndexCleanupResult>;

export function ClearVideoAutomaticTagOverride(arg1:number,arg2:string):Promise<void>;

export function ConfigureJellyfin(arg1:services.JellyfinConfigInput):Promise<services.JellyfinStatus>;

export function ConfirmCollectionSuggestion(arg1:number,arg2:string,arg3:Array<number>):Promise<services.CollectionDetail>;

export function ConfirmFaceClusterAppend(arg1:number):Promise<void>;

export function ConfirmFaceClusterAppendObservations(arg1:number,arg2:Array<number>):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function ConfirmSameSourceRelation(arg1:number):Promise<void>;

export function ControlPlaybackQueue(arg1:string,arg2:string):Promise<void>;

export function ConvertSubtitleToUTF8(arg1:number,arg2:string):Promise<services.SubtitleConvertResult>;

export function ConvertTagToPerson(arg1:services.TagPersonConversionRequest):Promise<services.TagPersonConversionResult>;

export function CountLibraryVideos(arg1:services.LibraryFilter):Promise<number>;

export function CreateBlankSubtitleDocument(arg1:number):Promise<services.SubtitleEditDocument>;

export function CreateCollection(arg1:string,arg2:string):Promise<models.MediaCollection>;

export function CreateDatabaseBackup():Promise<services.BackupFile>;

export function CreateEditProject(arg1:services.EditProjectCreateRequest):Promise<services.EditProjectView>;

export function CreateEnhancementTask(arg1:services.EnhancementCreateRequest):Promise<services.EnhancementTaskView>;

export function CreatePerson(arg1:string,arg2:string):Promise<models.Person>;

export function CreatePlaybackProxy(arg1:number):Promise<services.PlaybackProxyStatus>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function CreateTagCategory(arg1:string,arg2:Array<number>):Promise<void>;

export function CreateTagWithCategory(arg1:string,arg2:string,arg3:string):Promise<models.Tag>;

export function CreateVersionGroup(arg1:Array<number>,arg2:string):Promise<services.VersionGroupDetail>;

export function CreateWatchlistEntry(arg1:string,arg2:string):Promise<models.WatchlistEntry>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteDirectory(arg1:number):Promise<void>;

export function DeleteEditProject(arg1:number):Promise<void>;

export function DeleteGlossaryEntry(arg1:number):Promise<void>;

export function DeleteImageDirectory(arg1:number):Promise<void>;

export function DeleteImagesInDirectoryWithResult(arg1:string,arg2:boolean,arg3:string):Promise<services.BatchResult>;

export function DeleteImagesWithResult(arg1:Array<number>,arg2:boolean,arg3:string):Promise<services.BatchResult>;

export function DeletePerson(arg1:number):Promise<void>;

export function DeletePlaybackProxy(arg1:number):Promise<void>;

export function DeleteSavedLibraryView(arg1:number):Promise<void>;

export function DeleteStagedSources(arg1:Array<number>):Promise<services.StagedSourceDeleteResult>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTagCategory(arg1:string):Promise<void>;

export function DeleteVideoBookmark(arg1:number,arg2:number):Promise<void>;

export function DeleteVideosWithResult(arg1:Array<number>,arg2:boolean,arg3:string):Promise<services.BatchResult>;

export function DeleteViewingDiary(arg1:number,arg2:number):Promise<void>;

export function DeleteWatchlistEntry(arg1:number):Promise<void>;

export function DiscardEnhancementProgress(arg1:number):Promise<services.EnhancementTaskView>;

export function DiscardPendingSubtitle(arg1:number):Promise<void>;

export function DismissCleanupVideo(arg1:number,arg2:string):Promise<void>;

export function DismissClipCandidate(arg1:number,arg2:number):Promise<void>;

export function DismissCollectionSuggestion(arg1:number):Promise<void>;

export function DismissFaceClusterAppend(arg1:number):Promise<void>;

export function DismissImageNearDuplicateGroup(arg1:Array<number>):Promise<void>;

export function DismissImageNearDuplicateMember(arg1:Array<number>,arg2:number):Promise<void>;

export function DismissInterruptedSubtitleJobs():Promise<void>;

export function DismissNearDuplicateGroup(arg1:Array<number>):Promise<void>;

export function DismissNearDuplicateMember(arg1:Array<number>,arg2:number):Promise<void>;

export function DismissVersionGroupSuggestion(arg1:Array<number>):Promise<void>;

export function DissolveVersionGroup(arg1:number,arg2:number):Promise<void>;

export function DuplicateEditProject(arg1:number):Promise<services.EditProjectView>;

export function EditPlaybackQueue(arg1:services.QueueEdit):Promise<void>;

export function EnforcePlaybackProxyLimit():Promise<services.PlaybackProxyUsage>;

export function ExportLocalMetadataNFO(arg1:number):Promise<services.LocalMetadataNFOExportResult>;

export function ExportSystemHealthReport():Promise<main.HealthReportExport>;

export function FilterActivePersonIDs(arg1:Array<number>):Promise<services.ActivePersonIDsResult>;

export function FilterActiveTagIDs(arg1:Array<number>):Promise<services.ActiveTagIDsResult>;

export function FindSimilarVideos(arg1:services.SemanticSimilarRequest):Promise<services.SemanticSearchPage>;

export function ForceGenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function ForceRemoveTrashRecords(arg1:string,arg2:Array<number>,arg3:string):Promise<services.BatchResult>;

export function GenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function GetAIQualityReport(arg1:services.AIQualityFilter):Promise<services.AIQualityReport>;

export function GetAIReviewApproval(arg1:string,arg2:string,arg3:number,arg4:number):Promise<services.ReviewApprovalState>;

export function GetAIReviewCandidates(arg1:string,arg2:Array<number>):Promise<services.ReviewCandidateRefresh>;

export function GetAITaggingStatusSummary():Promise<services.AITaggingStatusSummary>;

export function GetAllDirectories():Promise<Array<models.ScanDirectory>>;

export function GetAllImageDirectories():Promise<Array<models.ImageDirectory>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetAutomaticOverrideKinds(arg1:Array<number>):Promise<Record<number, Array<string>>>;

export function GetBackgroundTasks():Promise<Array<string>>;

export function GetBackupStatus():Promise<services.BackupStatus>;

export function GetBrowserBridgeStatus():Promise<services.BrowserBridgeStatus>;

export function GetCleanupConsolidationReview(arg1:number):Promise<services.CleanupConsolidationReview>;

export function GetCleanupConsolidationStatus(arg1:number):Promise<services.CleanupConsolidationStatus>;

export function GetCleanupStatus():Promise<services.CleanupStatus>;

export function GetCollectionDetail(arg1:number):Promise<services.CollectionDetail>;

export function GetCollectionSuggestionStatus():Promise<services.CollectionSuggestionStatus>;

export function GetDatabaseBackendStatus():Promise<services.DatabaseBackendStatus>;

export function GetDatabaseSwitchStatus():Promise<services.DatabaseSwitchStatus>;

export function GetEditProject(arg1:number):Promise<services.EditProjectView>;

export function GetEnhancementCapability():Promise<services.EnhancementRuntimeCapability>;

export function GetEnhancementModelStatus():Promise<services.EnhancementModelStatus>;

export function GetEnhancementVideoPreflight(arg1:number):Promise<services.EnhancementVideoPreflight>;

export function GetFaceAnalysisStatus():Promise<services.FaceAnalysisStatus>;

export function GetFaceClusterObservations(arg1:number,arg2:number,arg3:number):Promise<services.FaceClusterObservationPage>;

export function GetFaceDataUsage():Promise<services.FaceDataUsage>;

export function GetFaceRuntimeStatus():Promise<services.FaceRuntimeStatus>;

export function GetFrameHashBackfillStatus():Promise<services.FrameHashStatus>;

export function GetIINASyncStatus():Promise<services.IINASyncStatus>;

export function GetIdleSchedulerStatus():Promise<services.IdleSchedulerStatus>;

export function GetImageAITaggingStatus():Promise<services.ImageAITaggingStatus>;

export function GetImageAITaggingSummary():Promise<services.ImageAITaggingSummary>;

export function GetImageCleanupStatus():Promise<services.ImageCleanupStatus>;

export function GetImageDetail(arg1:number):Promise<services.ImageDetail>;

export function GetImageEXIFBackfillStatus():Promise<services.ImageEXIFBackfillStatus>;

export function GetImageInsights():Promise<services.ImageStats>;

export function GetImagePerceptualHashBackfillStatus():Promise<services.ImagePerceptualHashBackfillStatus>;

export function GetImageSemanticIndexStatus():Promise<services.ImageSemanticIndexStatus>;

export function GetImageTags():Promise<Array<models.Tag>>;

export function GetInterruptedSubtitleJobs():Promise<services.SubtitleInterruptedJobs>;

export function GetJellyfinDiagnostics():Promise<services.JellyfinDiagnostics>;

export function GetJellyfinStatus():Promise<services.JellyfinStatus>;

export function GetLibraryCounts():Promise<services.LibraryCounts>;

export function GetLibraryInsights():Promise<services.LibraryStats>;

export function GetLibrarySubtitleHits(arg1:string,arg2:Array<number>):Promise<Array<services.LibrarySubtitleHit>>;

export function GetLibraryWatcherStatus():Promise<services.LibraryWatcherStatus>;

export function GetLocalMetadataBackfillStatus():Promise<services.LocalMetadataBackfillStatus>;

export function GetLocalMetadataExportStatus():Promise<services.LocalMetadataExportStatus>;

export function GetPendingWorkSummary():Promise<main.PendingWorkSummary>;

export function GetPerceptualHashBackfillStatus():Promise<services.PerceptualHashStatus>;

export function GetPersonDeletionImpact(arg1:number):Promise<services.PersonDeletionImpact>;

export function GetPersonDetail(arg1:number,arg2:number,arg3:number):Promise<services.PersonDetail>;

export function GetPersonImages(arg1:number,arg2:number,arg3:number):Promise<services.PersonImagePage>;

export function GetPlaybackProxy(arg1:number):Promise<services.PlaybackProxyView>;

export function GetPlaybackProxyStatus():Promise<services.PlaybackProxyStatus>;

export function GetPlaybackProxyUsage():Promise<services.PlaybackProxyUsage>;

export function GetPlaybackQueue(arg1:services.QueueQuery):Promise<services.QueueSnapshot>;

export function GetPreviewSession(arg1:number):Promise<services.PreviewSession>;

export function GetSceneCoverage(arg1:services.LibraryFilter):Promise<services.SceneCoverage>;

export function GetSceneIndexStatus():Promise<services.SceneIndexStatus>;

export function GetSceneRuntimeStatus():Promise<services.SceneRuntimeStatus>;

export function GetSemanticIndexStatus():Promise<services.SemanticIndexStatus>;

export function GetSettings():Promise<models.Settings>;

export function GetShortFeedAccessStatus():Promise<services.ShortFeedAccessStatus>;

export function GetShortFeedQRCode():Promise<string>;

export function GetShortFeedServerStatus():Promise<services.ShortFeedServerStatus>;

export function GetStartupError():Promise<string>;

export function GetSubtitleEditDocument(arg1:number):Promise<services.SubtitleEditDocument>;

export function GetSubtitleEngineStatuses():Promise<Array<services.SubtitleEngineStatus>>;

export function GetSubtitleIndexSyncStatus():Promise<services.SubtitleIndexSyncStatus>;

export function GetSubtitleOverwriteInfo(arg1:number):Promise<services.SubtitleOverwriteInfo>;

export function GetSubtitleQueueState():Promise<services.SubtitleQueueSnapshot>;

export function GetSubtitleSegments(arg1:number):Promise<Array<subtitleparser.Segment>>;

export function GetSystemHealthSection(arg1:string):Promise<main.HealthSection>;

export function GetTagUsageCounts(arg1:Array<number>):Promise<Record<number, services.TagUsageCount>>;

export function GetTaskCenterSnapshot():Promise<main.TaskCenterSnapshot>;

export function GetTechnicalBackfillStatus():Promise<services.TechnicalBackfillStatus>;

export function GetTrashUsage():Promise<services.TrashUsage>;

export function GetVersionGroup(arg1:number):Promise<services.VersionGroupDetail>;

export function GetVideoAutomaticTagOverrides(arg1:number):Promise<Array<models.VideoAutomaticTagOverride>>;

export function GetVideoDetails(arg1:number):Promise<services.VideoDetails>;

export function GetVideoEditStatus():Promise<services.VideoEditStatus>;

export function GetVideosByIDs(arg1:Array<number>):Promise<Array<models.Video>>;

export function GetViewingYearReview(arg1:number):Promise<services.ViewingYearReview>;

export function GetWallpaperPreflight(arg1:string,arg2:number):Promise<services.WallpaperPreflight>;

export function GetWallpaperStatus():Promise<services.WallpaperStatus>;

export function IgnoreFaceCluster(arg1:number):Promise<void>;

export function LinkFaceCluster(arg1:number,arg2:number):Promise<services.FaceClusterView>;

export function LinkMovieToVideo(arg1:string,arg2:number):Promise<void>;

export function ListAITagCandidatePage(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<services.AITagCandidatePage>;

export function ListCleanupDismissals(arg1:string,arg2:number,arg3:number):Promise<services.CleanupDismissalPage>;

export function ListCollectionSuggestions():Promise<Array<services.CollectionSuggestionView>>;

export function ListCollections(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<services.CollectionListItem>>;

export function ListContinueWatchingWithFilter(arg1:services.LibraryFilter,arg2:string,arg3:number,arg4:number):Promise<services.LibraryVideoPage>;

export function ListDatabaseBackups():Promise<Array<services.BackupFile>>;

export function ListDownloadTasks():Promise<Array<services.BrowserDownloadTask>>;

export function ListEditProjects(arg1:number):Promise<Array<services.EditProjectSummary>>;

export function ListEnhancementTasks(arg1:number):Promise<Array<services.EnhancementTaskView>>;

export function ListFaceClusterPage(arg1:services.FaceClusterFilter,arg2:services.FaceClusterCursorKey,arg3:number):Promise<services.FaceClusterPage>;

export function ListGlossaryEntries(arg1:number):Promise<Array<models.TranslationGlossaryEntry>>;

export function ListHiddenImages(arg1:number,arg2:number):Promise<services.HiddenImagePage>;

export function ListIgnoredFaceClusters(arg1:number,arg2:number):Promise<services.IgnoredFaceClusterPage>;

export function ListImageAITagCandidatePage(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<services.ImageAITagCandidatePage>;

export function ListImageAITagCandidates(arg1:number,arg2:string,arg3:string):Promise<Array<services.ImageAITaggingReviewItem>>;

export function ListImageFolderGroups(arg1:services.ImageFilter):Promise<Array<services.ImageFolderGroup>>;

export function ListImageTimelineBuckets(arg1:services.ImageFilter):Promise<Array<services.ImageTimelineBucket>>;

export function ListMovieChart(arg1:number,arg2:string,arg3:number,arg4:boolean):Promise<services.MovieChartPage>;

export function ListMovieChartYears():Promise<Array<number>>;

export function ListMovieVideoLinks(arg1:string):Promise<Array<services.LinkedVideoView>>;

export function ListPeople(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<services.PersonListItem>>;

export function ListRecentlyPlayedWithFilter(arg1:services.LibraryFilter,arg2:string,arg3:number,arg4:number):Promise<Array<models.Video>>;

export function ListSameSourceRelations(arg1:string,arg2:boolean):Promise<Array<services.VideoSameSourceReviewItem>>;

export function ListSavedLibraryViews():Promise<Array<models.SavedLibraryView>>;

export function ListStagedSources():Promise<Array<models.MigrationStagedSource>>;

export function ListStaleReasonCounts():Promise<Record<string, number>>;

export function ListSubtitleBackups(arg1:number):Promise<Array<services.SubtitleBackup>>;

export function ListTagPersonConversions(arg1:number):Promise<Array<services.TagPersonConversionRecord>>;

export function ListTrashEntries(arg1:services.TrashFilter):Promise<services.TrashPage>;

export function ListUnconfirmedPlaybackHistory(arg1:services.HistoryQuery):Promise<services.PlaybackHistoryPage>;

export function ListVersionGroupSuggestions(arg1:number):Promise<Array<services.VersionGroupSuggestion>>;

export function ListVersionGroups(arg1:number,arg2:number):Promise<services.VersionGroupPage>;

export function ListVideoBookmarks(arg1:services.BookmarkQuery):Promise<services.BookmarkPage>;

export function ListViewingDiary(arg1:services.DiaryQuery):Promise<services.DiaryPage>;

export function ListWatchedMovies():Promise<Array<services.WatchedMovieYearGroup>>;

export function ListWatchlist(arg1:string,arg2:number,arg3:number):Promise<services.WatchlistPage>;

export function ListWatchlistCandidates(arg1:number):Promise<Array<services.WatchlistCandidateView>>;

export function LogFrontend(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MarkMovieChartEntry(arg1:string,arg2:string):Promise<services.MovieChartMarkResult>;

export function MarkSameSourceRelationRead(arg1:number):Promise<void>;

export function MergeMediaMetadata(arg1:string,arg2:number,arg3:Array<number>,arg4:services.MediaMetadataMergeOptions):Promise<services.MediaMetadataMergeResult>;

export function MergePeople(arg1:number,arg2:Array<number>):Promise<services.MergePeopleResult>;

export function MergeTags(arg1:Array<number>,arg2:number):Promise<services.MergeTagsResult>;

export function MoveDirectory(arg1:string,arg2:string):Promise<services.FolderMigrationResult>;

export function MoveVideo(arg1:number,arg2:string):Promise<services.FileMigrationResult>;

export function NameFaceCluster(arg1:number,arg2:string,arg3:string):Promise<services.FaceClusterView>;

export function NextPlaybackQueue(arg1:string,arg2:number):Promise<void>;

export function OpenDirectory(arg1:number):Promise<void>;

export function OpenImageDirectory(arg1:string):Promise<void>;

export function OpenMovieChartYear(arg1:number):Promise<boolean>;

export function PermanentlyDeleteImages(arg1:Array<number>):Promise<services.BatchResult>;

export function PermanentlyDeleteVideos(arg1:Array<number>):Promise<services.BatchResult>;

export function PickRandomVideos(arg1:services.RandomPlayRequest,arg2:number):Promise<services.RandomPickResult>;

export function PlayPlaybackQueue(arg1:number,arg2:number):Promise<void>;

export function PlayRandomVideoWithFilter(arg1:services.RandomPlayRequest):Promise<services.PlaybackAttemptResult>;

export function PlayVideo(arg1:number):Promise<services.PlaybackAttemptResult>;

export function PreflightDatabaseSwitch(arg1:string):Promise<services.DatabaseSwitchPreflight>;

export function PreflightEditProject(arg1:number):Promise<services.EditPreflight>;

export function PrepareFaceRuntime():Promise<services.FaceRuntimeStatus>;

export function PrepareSceneRuntime():Promise<services.SceneRuntimeStatus>;

export function PrepareSubtitleEngine(arg1:services.SubtitleEngine):Promise<void>;

export function PreviewAIReviewApproval(arg1:string,arg2:services.ReviewApprovalRequest):Promise<services.ReviewApprovalPreview>;

export function PreviewCleanupConsolidation(arg1:services.CleanupConsolidationRequest):Promise<services.CleanupConsolidationPreview>;

export function PreviewExternally(arg1:number):Promise<void>;

export function PreviewFaceClusterUnlink(arg1:number):Promise<Array<services.FaceUnlinkMediaView>>;

export function PreviewLocalMetadataBatch(arg1:Array<number>):Promise<services.LocalMetadataBatchPreview>;

export function PreviewTagPersonConversion(arg1:number):Promise<services.TagPersonConversionPreview>;

export function PurgeTrashEntries(arg1:string,arg2:Array<number>):Promise<services.BatchResult>;

export function QueueEditProject(arg1:services.EditQueueRequest):Promise<services.EditQueueResult>;

export function ReaddRemovedRoot(arg1:number):Promise<string>;

export function ReassignFaceCluster(arg1:number,arg2:number,arg3:boolean):Promise<services.FaceClusterView>;

export function RecheckImages(arg1:Array<number>):Promise<services.ImageScanResult>;

export function RecheckVideos(arg1:Array<number>):Promise<services.LibraryReconcileSummary>;

export function RecordViewEvent(arg1:number,arg2:string,arg3:string):Promise<boolean>;

export function RefreshMovieChart(arg1:number):Promise<void>;

export function RefreshVideoTechnicalMetadata(arg1:number):Promise<services.VideoDetails>;

export function RegenerateBrowserBridgeToken():Promise<string>;

export function ReimportDownload(arg1:string):Promise<services.BrowserDownloadActionResult>;

export function RejectAITagCandidate(arg1:number):Promise<void>;

export function RejectAITagCandidatesByVideo(arg1:number):Promise<number>;

export function RejectImageAITagCandidate(arg1:number):Promise<void>;

export function RejectImageAITagCandidatesByImage(arg1:number):Promise<number>;

export function RejectSameSourceRelation(arg1:number):Promise<void>;

export function RelaunchApp():Promise<services.RelaunchResult>;

export function RelocateVideo(arg1:number,arg2:string):Promise<void>;

export function RemoveCollectionCover(arg1:number):Promise<void>;

export function RemoveCollectionVideo(arg1:number,arg2:number):Promise<void>;

export function RemoveFaceClusterObservation(arg1:number,arg2:number):Promise<boolean>;

export function RemoveGoneTrashEntries(arg1:string,arg2:Array<number>):Promise<services.BatchResult>;

export function RemovePersonAvatar(arg1:number):Promise<void>;

export function RemovePersonImage(arg1:number,arg2:number):Promise<boolean>;

export function RemovePersonVideo(arg1:number,arg2:number):Promise<boolean>;

export function RemoveTagFromImage(arg1:number,arg2:number):Promise<void>;

export function RemoveTagFromVideo(arg1:number,arg2:number):Promise<void>;

export function RemoveVersionMember(arg1:number,arg2:number,arg3:number):Promise<services.VersionGroupDetail>;

export function RenameDirectory(arg1:string,arg2:string):Promise<services.FolderMigrationResult>;

export function RenameTagCategory(arg1:string,arg2:string):Promise<void>;

export function RenameVideo(arg1:number,arg2:string):Promise<void>;

export function ReorderCollectionVideos(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderVersionMembers(arg1:number,arg2:number,arg3:Array<number>):Promise<services.VersionGroupDetail>;

export function ReportInlineQueuePlayback(arg1:services.InlineQueueEvent):Promise<void>;

export function RequeueEditProject(arg1:services.EditQueueRequest):Promise<services.EditQueueResult>;

export function RequeueInterruptedSubtitleJobs():Promise<number>;

export function RerollRandom(arg1:string):Promise<services.PlaybackAttemptResult>;

export function ResolveSubtitleJob(arg1:number,arg2:string):Promise<services.SubtitleJobResolveResult>;

export function ResolveVideoBookmark(arg1:number):Promise<services.BookmarkResolution>;

export function RestoreDatabaseBackup(arg1:services.BackupRestoreRequest):Promise<void>;

export function RestoreFaceCluster(arg1:number):Promise<void>;

export function RestoreSubtitleBackup(arg1:number,arg2:string):Promise<services.SubtitleRestoreResult>;

export function RestoreTrashBatch(arg1:string,arg2:string):Promise<services.BatchResult>;

export function RestoreTrashEntries(arg1:string,arg2:Array<number>):Promise<services.BatchResult>;

export function RetranslateSubtitleEntries(arg1:services.SubtitleRetranslateRequest):Promise<services.SubtitleRetranslateResult>;

export function RetryAITagging(arg1:number):Promise<void>;

export function RetryDownload(arg1:string):Promise<services.BrowserDownloadActionResult>;

export function RetryEnhancementTask(arg1:number):Promise<services.EnhancementTaskView>;

export function RetryImageAITagging(arg1:number):Promise<Array<models.ImageAITagCandidate>>;

export function RetryLibraryWatcherRoot(arg1:number):Promise<services.LibraryWatchRootStatus>;

export function RetryWatchlistEnrichment(arg1:number):Promise<void>;

export function RevealBackupDirectory():Promise<void>;

export function RevealDownload(arg1:string):Promise<services.BrowserDownloadActionResult>;

export function RevealImage(arg1:number):Promise<void>;

export function RunGatedTaskNow(arg1:string):Promise<void>;

export function SaveLibraryView(arg1:services.SavedLibraryViewInput):Promise<models.SavedLibraryView>;

export function SaveSubtitleEditDocument(arg1:services.SubtitleSaveRequest):Promise<services.SubtitleSaveResult>;

export function SaveVideoBookmark(arg1:services.BookmarkInput):Promise<services.BookmarkDTO>;

export function SaveViewingDiary(arg1:services.DiaryInput):Promise<services.DiaryEntryDTO>;

export function SearchAITagCandidatePage(arg1:services.ReviewSearchRequest):Promise<services.AITagCandidatePage>;

export function SearchImageAITagCandidatePage(arg1:services.ReviewSearchRequest):Promise<services.ImageAITagCandidatePage>;

export function SearchImagePage(arg1:services.ImagePageRequest):Promise<services.ImagePage>;

export function SearchImagesSemantic(arg1:services.ImageSemanticSearchRequest):Promise<services.ImageSemanticSearchPage>;

export function SearchLibraryVideoPage(arg1:services.LibraryVideoPageRequest):Promise<services.LibraryVideoPage>;

export function SearchScenes(arg1:services.SceneSearchRequest):Promise<services.SceneSearchResult>;

export function SearchSemanticVideos(arg1:services.SemanticSearchRequest):Promise<services.SemanticSearchPage>;

export function SelectBrowserDownloadDirectory():Promise<string>;

export function SelectCollectionCover():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFolderToRename():Promise<string>;

export function SelectMigrationDestinationDirectory():Promise<string>;

export function SelectMigrationSourceDirectory():Promise<string>;

export function SelectPersonAvatar():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function SetCollectionCover(arg1:number,arg2:string):Promise<models.MediaCollection>;

export function SetImageFavorite(arg1:number,arg2:boolean):Promise<models.Image>;

export function SetImageRating(arg1:number,arg2:any):Promise<models.Image>;

export function SetPersonAvatar(arg1:number,arg2:string):Promise<models.Person>;

export function SetShortFeedEnabled(arg1:boolean):Promise<void>;

export function SetShortFeedPIN(arg1:string):Promise<void>;

export function SetVideoFavorite(arg1:number,arg2:boolean):Promise<models.Video>;

export function SetVideoLiked(arg1:number,arg2:boolean):Promise<models.Video>;

export function SetVideoWatched(arg1:number,arg2:boolean):Promise<models.Video>;

export function SetWallpaper(arg1:string,arg2:number):Promise<services.WallpaperStatus>;

export function SetWindowForeground(arg1:boolean):Promise<void>;

export function StartAIReviewApproval(arg1:string,arg2:string):Promise<services.ReviewApprovalState>;

export function StartCleanupAnalysisFromSettings():Promise<services.CleanupStatus>;

export function StartCleanupConsolidation(arg1:string,arg2:boolean):Promise<services.CleanupConsolidationStatus>;

export function StartCollectionSuggestionAnalysis():Promise<services.CollectionSuggestionStatus>;

export function StartDatabaseSwitch(arg1:string):Promise<void>;

export function StartEnhancementModelDownload():Promise<services.EnhancementModelStatus>;

export function StartFaceAnalysis(arg1:string):Promise<services.FaceAnalysisStatus>;

export function StartFrameHashBackfill():Promise<services.FrameHashStatus>;

export function StartImageAITagging():Promise<services.ImageAITaggingStatus>;

export function StartImageCleanupAnalysis():Promise<services.ImageCleanupStatus>;

export function StartImageEXIFBackfill():Promise<services.ImageEXIFBackfillStatus>;

export function StartImagePerceptualHashBackfill():Promise<services.ImagePerceptualHashBackfillStatus>;

export function StartImageSemanticIndex():Promise<services.ImageSemanticIndexStatus>;

export function StartLocalMetadataBackfill():Promise<services.LocalMetadataBackfillStatus>;

export function StartLocalMetadataExport(arg1:services.LocalMetadataExportRequest):Promise<services.LocalMetadataExportStatus>;

export function StartPerceptualHashBackfill():Promise<services.PerceptualHashStatus>;

export function StartSceneIndex(arg1:services.SceneIndexRequest):Promise<services.SceneIndexStatus>;

export function StartSemanticIndex(arg1:services.SemanticIndexBuildRequest):Promise<services.SemanticIndexStatus>;

export function StartTechnicalBackfill():Promise<services.TechnicalBackfillStatus>;

export function StopPlaybackQueue(arg1:string):Promise<void>;

export function StopVideoWallpaper():Promise<services.WallpaperStatus>;

export function SuggestLibraryMatchesBatch(arg1:Array<services.LibraryMatchQuery>):Promise<Record<string, Array<services.LibraryMatchSuggestion>>>;

export function SuggestTonightVideos(arg1:services.TonightRequest):Promise<Array<services.TonightSuggestion>>;

export function SwitchBackendConfigOnly(arg1:string):Promise<services.DatabaseSwitchConfigResult>;

export function SyncDirectoryWithProgress(arg1:string,arg2:string):Promise<services.ScanSyncResult>;

export function SyncImageDirectories():Promise<services.ImageScanResult>;

export function SyncScanDirectories(arg1:string):Promise<services.ScanSyncResult>;

export function SyncSubtitleIndexNow():Promise<services.SubtitleIndexSyncStatus>;

export function TestAITaggingConnection(arg1:services.AITaggingConnectionTestInput):Promise<services.AITaggingConnectionTestResult>;

export function TestWatchlistMetadataConnection(arg1:services.WatchlistMetadataProbeInput):Promise<services.WatchlistMetadataProbeResult>;

export function TranslateSubtitle(arg1:services.SubtitleTranslateRequest):Promise<services.SubtitleTranslateResult>;

export function TrashStagedSources(arg1:Array<number>):Promise<services.BatchResult>;

export function TriggerAITagging():Promise<boolean>;

export function UndoCleanupDismissals(arg1:string,arg2:Array<number>):Promise<services.CleanupDismissalUndoResult>;

export function UndoTagPersonConversion(arg1:number):Promise<services.TagPersonConversionUndoResult>;

export function UnlinkFaceCluster(arg1:number,arg2:boolean):Promise<services.FaceClusterView>;

export function UnlinkMovieVideo(arg1:string,arg2:number):Promise<void>;

export function UnlockShortFeedLogin():Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string):Promise<models.MediaCollection>;

export function UpdateDirectoryWithMode(arg1:number,arg2:string,arg3:string,arg4:string):Promise<services.DirectoryUpdateResult>;

export function UpdateEditRecipe(arg1:services.EditRecipeUpdateRequest):Promise<services.EditProjectView>;

export function UpdateImageDirectory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdatePerson(arg1:number,arg2:string,arg3:string):Promise<models.Person>;

export function UpdateSavedLibraryView(arg1:number,arg2:string,arg3:services.LibraryFilter):Promise<models.SavedLibraryView>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateTagWithCategory(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateVersionGroup(arg1:number,arg2:number,arg3:string,arg4:Record<number, string>):Promise<services.VersionGroupDetail>;

export function UpdateVideoDetails(arg1:services.VideoDetailsUpdate):Promise<services.VideoDetails>;

export function UpdateVideoRating(arg1:number,arg2:any):Promise<models.Video>;

export function UpdateVideoWatchProgress(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:string):Promise<models.Video>;

export function UpdateWatchlistEntry(arg1:number,arg2:string):Promise<void>;

export function UpsertGlossaryEntry(arg1:models.TranslationGlossaryEntry):Promise<models.TranslationGlossaryEntry>;

export function ValidateScanDirectory(arg1:string):Promise<services.ScanDirectoryValidation>;
