// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionVideo'](arg1, arg2);
}

export function AddCollectionVideos(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionVideos'](arg1, arg2);
}

export function AddDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2);
}

export function AddPersonVideo(arg1, arg2) {
  return window['go']['main']['App']['AddPersonVideo'](arg1, arg2);
}

export function AddPersonVideos(arg1, arg2) {
  return window['go']['main']['App']['AddPersonVideos'](arg1, arg2);
}

export function AddTagToVideo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToVideo'](arg1, arg2);
}

export function AddVideo(arg1) {
  return window['go']['main']['App']['AddVideo'](arg1);
}

export function ApplyLocalMetadata(arg1) {
  return window['go']['main']['App']['ApplyLocalMetadata'](arg1);
}

export function ApplyLocalMetadataBatch(arg1) {
  return window['go']['main']['App']['ApplyLocalMetadataBatch'](arg1);
}

export function ApproveAITagCandidate(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidate'](arg1);
}

export function BatchAddTagToVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToVideos'](arg1, arg2);
}

export function BatchDeleteVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteVideos'](arg1, arg2);
}

export function BatchMoveVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchMoveVideos'](arg1, arg2);
}

export function BatchRefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['BatchRefreshVideoMetadata'](arg1);
}

export function BatchRemoveTagFromVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromVideos'](arg1, arg2);
}

export function CancelEnhancementTask(arg1) {
  return window['go']['main']['App']['CancelEnhancementTask'](arg1);
}

export function CancelLocalMetadataBackfill() {
  return window['go']['main']['App']['CancelLocalMetadataBackfill']();
}

export function CancelLocalMetadataExport() {
  return window['go']['main']['App']['CancelLocalMetadataExport']();
}

export function CancelPerceptualHashBackfill() {
  return window['go']['main']['App']['CancelPerceptualHashBackfill']();
}

export function CancelSemanticIndex() {
  return window['go']['main']['App']['CancelSemanticIndex']();
}

export function CancelSubtitle() {
  return window['go']['main']['App']['CancelSubtitle']();
}

export function CancelSubtitleTask(arg1) {
  return window['go']['main']['App']['CancelSubtitleTask'](arg1);
}

export function CancelTechnicalBackfill() {
  return window['go']['main']['App']['CancelTechnicalBackfill']();
}

export function CheckSubtitleDependencies() {
  return window['go']['main']['App']['CheckSubtitleDependencies']();
}

export function ConfirmSameSourceRelation(arg1) {
  return window['go']['main']['App']['ConfirmSameSourceRelation'](arg1);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateDatabaseBackup() {
  return window['go']['main']['App']['CreateDatabaseBackup']();
}

export function CreateEnhancementTask(arg1) {
  return window['go']['main']['App']['CreateEnhancementTask'](arg1);
}

export function CreatePerson(arg1, arg2) {
  return window['go']['main']['App']['CreatePerson'](arg1, arg2);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteSavedLibraryView(arg1) {
  return window['go']['main']['App']['DeleteSavedLibraryView'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteVideo(arg1, arg2) {
  return window['go']['main']['App']['DeleteVideo'](arg1, arg2);
}

export function DismissNearDuplicateGroup(arg1) {
  return window['go']['main']['App']['DismissNearDuplicateGroup'](arg1);
}

export function DownloadSubtitleDependencies() {
  return window['go']['main']['App']['DownloadSubtitleDependencies']();
}

export function ExportLocalMetadataNFO(arg1) {
  return window['go']['main']['App']['ExportLocalMetadataNFO'](arg1);
}

export function FindSimilarVideos(arg1) {
  return window['go']['main']['App']['FindSimilarVideos'](arg1);
}

export function ForceGenerateSubtitle(arg1) {
  return window['go']['main']['App']['ForceGenerateSubtitle'](arg1);
}

export function GenerateSubtitle(arg1) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1);
}

export function GetAIQualityReport(arg1) {
  return window['go']['main']['App']['GetAIQualityReport'](arg1);
}

export function GetAITagLibrary() {
  return window['go']['main']['App']['GetAITagLibrary']();
}

export function GetAITaggingStatusSummary() {
  return window['go']['main']['App']['GetAITaggingStatusSummary']();
}

export function GetAllDirectories() {
  return window['go']['main']['App']['GetAllDirectories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllVideos() {
  return window['go']['main']['App']['GetAllVideos']();
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetCleanupCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCleanupCandidates'](arg1, arg2, arg3);
}

export function GetCleanupStatus() {
  return window['go']['main']['App']['GetCleanupStatus']();
}

export function GetCollectionDetail(arg1) {
  return window['go']['main']['App']['GetCollectionDetail'](arg1);
}

export function GetEnhancementCapability() {
  return window['go']['main']['App']['GetEnhancementCapability']();
}

export function GetEnhancementVideoPreflight(arg1) {
  return window['go']['main']['App']['GetEnhancementVideoPreflight'](arg1);
}

export function GetLibraryInsights() {
  return window['go']['main']['App']['GetLibraryInsights']();
}

export function GetLibrarySubtitleHits(arg1, arg2) {
  return window['go']['main']['App']['GetLibrarySubtitleHits'](arg1, arg2);
}

export function GetLibraryWatcherStatus() {
  return window['go']['main']['App']['GetLibraryWatcherStatus']();
}

export function GetLocalMetadataBackfillStatus() {
  return window['go']['main']['App']['GetLocalMetadataBackfillStatus']();
}

export function GetLocalMetadataDiff(arg1) {
  return window['go']['main']['App']['GetLocalMetadataDiff'](arg1);
}

export function GetLocalMetadataExportStatus() {
  return window['go']['main']['App']['GetLocalMetadataExportStatus']();
}

export function GetPerceptualHashBackfillStatus() {
  return window['go']['main']['App']['GetPerceptualHashBackfillStatus']();
}

export function GetPersonDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPersonDetail'](arg1, arg2, arg3);
}

export function GetPreviewSession(arg1) {
  return window['go']['main']['App']['GetPreviewSession'](arg1);
}

export function GetSemanticIndexStatus() {
  return window['go']['main']['App']['GetSemanticIndexStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShortFeedServerStatus() {
  return window['go']['main']['App']['GetShortFeedServerStatus']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetSubtitleEditDocument(arg1) {
  return window['go']['main']['App']['GetSubtitleEditDocument'](arg1);
}

export function GetSubtitleEngineStatuses() {
  return window['go']['main']['App']['GetSubtitleEngineStatuses']();
}

export function GetSubtitleQueueState() {
  return window['go']['main']['App']['GetSubtitleQueueState']();
}

export function GetSubtitleSegments(arg1) {
  return window['go']['main']['App']['GetSubtitleSegments'](arg1);
}

export function GetTechnicalBackfillStatus() {
  return window['go']['main']['App']['GetTechnicalBackfillStatus']();
}

export function GetVideoDetails(arg1) {
  return window['go']['main']['App']['GetVideoDetails'](arg1);
}

export function GetVideosByDirectory(arg1) {
  return window['go']['main']['App']['GetVideosByDirectory'](arg1);
}

export function GetVideosPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVideosPaginated'](arg1, arg2, arg3, arg4);
}

export function ListAITagCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAITagCandidates'](arg1, arg2, arg3);
}

export function ListCollections(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListCollections'](arg1, arg2, arg3, arg4);
}

export function ListDatabaseBackups() {
  return window['go']['main']['App']['ListDatabaseBackups']();
}

export function ListEnhancementTasks(arg1) {
  return window['go']['main']['App']['ListEnhancementTasks'](arg1);
}

export function ListPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPeople'](arg1, arg2, arg3, arg4);
}

export function ListRecentlyPlayed(arg1) {
  return window['go']['main']['App']['ListRecentlyPlayed'](arg1);
}

export function ListRecentlyPlayedWithFilter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRecentlyPlayedWithFilter'](arg1, arg2, arg3, arg4);
}

export function ListSameSourceRelations(arg1, arg2) {
  return window['go']['main']['App']['ListSameSourceRelations'](arg1, arg2);
}

export function ListSavedLibraryViews() {
  return window['go']['main']['App']['ListSavedLibraryViews']();
}

export function ListTrashEntries() {
  return window['go']['main']['App']['ListTrashEntries']();
}

export function LogFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3);
}

export function MarkSameSourceRelationRead(arg1) {
  return window['go']['main']['App']['MarkSameSourceRelationRead'](arg1);
}

export function MergeTags(arg1, arg2) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2);
}

export function MoveDirectory(arg1, arg2) {
  return window['go']['main']['App']['MoveDirectory'](arg1, arg2);
}

export function MoveVideo(arg1, arg2) {
  return window['go']['main']['App']['MoveVideo'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function PlayRandomVideo() {
  return window['go']['main']['App']['PlayRandomVideo']();
}

export function PlayRandomVideoWithFilter(arg1) {
  return window['go']['main']['App']['PlayRandomVideoWithFilter'](arg1);
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function PrepareSubtitleEngine(arg1) {
  return window['go']['main']['App']['PrepareSubtitleEngine'](arg1);
}

export function PreviewExternally(arg1) {
  return window['go']['main']['App']['PreviewExternally'](arg1);
}

export function PreviewLocalMetadataBatch(arg1) {
  return window['go']['main']['App']['PreviewLocalMetadataBatch'](arg1);
}

export function RefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoMetadata'](arg1);
}

export function RefreshVideoTechnicalMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoTechnicalMetadata'](arg1);
}

export function RejectAITagCandidate(arg1) {
  return window['go']['main']['App']['RejectAITagCandidate'](arg1);
}

export function RejectAITagCandidatesByVideo(arg1) {
  return window['go']['main']['App']['RejectAITagCandidatesByVideo'](arg1);
}

export function RejectSameSourceRelation(arg1) {
  return window['go']['main']['App']['RejectSameSourceRelation'](arg1);
}

export function RelocateVideo(arg1, arg2) {
  return window['go']['main']['App']['RelocateVideo'](arg1, arg2);
}

export function RemoveCollectionCover(arg1) {
  return window['go']['main']['App']['RemoveCollectionCover'](arg1);
}

export function RemoveCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveCollectionVideo'](arg1, arg2);
}

export function RemovePersonAvatar(arg1) {
  return window['go']['main']['App']['RemovePersonAvatar'](arg1);
}

export function RemovePersonVideo(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonVideo'](arg1, arg2);
}

export function RemoveTagFromVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromVideo'](arg1, arg2);
}

export function RenameDirectory(arg1, arg2) {
  return window['go']['main']['App']['RenameDirectory'](arg1, arg2);
}

export function RenameVideo(arg1, arg2) {
  return window['go']['main']['App']['RenameVideo'](arg1, arg2);
}

export function ReorderCollectionVideos(arg1, arg2) {
  return window['go']['main']['App']['ReorderCollectionVideos'](arg1, arg2);
}

export function ResolveVideoArtwork(arg1, arg2) {
  return window['go']['main']['App']['ResolveVideoArtwork'](arg1, arg2);
}

export function RestoreDatabaseBackup(arg1) {
  return window['go']['main']['App']['RestoreDatabaseBackup'](arg1);
}

export function RestoreTrashEntry(arg1) {
  return window['go']['main']['App']['RestoreTrashEntry'](arg1);
}

export function RetranslateSubtitleEntries(arg1) {
  return window['go']['main']['App']['RetranslateSubtitleEntries'](arg1);
}

export function RetryAITagging(arg1) {
  return window['go']['main']['App']['RetryAITagging'](arg1);
}

export function RetryEnhancementTask(arg1) {
  return window['go']['main']['App']['RetryEnhancementTask'](arg1);
}

export function RetryLibraryWatcherRoot(arg1) {
  return window['go']['main']['App']['RetryLibraryWatcherRoot'](arg1);
}

export function SaveAITagLibrary(arg1) {
  return window['go']['main']['App']['SaveAITagLibrary'](arg1);
}

export function SaveLibraryView(arg1) {
  return window['go']['main']['App']['SaveLibraryView'](arg1);
}

export function SaveSubtitleEditDocument(arg1) {
  return window['go']['main']['App']['SaveSubtitleEditDocument'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function ScanDirectoryWithInfo(arg1) {
  return window['go']['main']['App']['ScanDirectoryWithInfo'](arg1);
}

export function SearchLibraryVideoPage(arg1) {
  return window['go']['main']['App']['SearchLibraryVideoPage'](arg1);
}

export function SearchLibraryVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchLibraryVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchSemanticVideos(arg1) {
  return window['go']['main']['App']['SearchSemanticVideos'](arg1);
}

export function SearchSubtitleMatches(arg1, arg2) {
  return window['go']['main']['App']['SearchSubtitleMatches'](arg1, arg2);
}

export function SearchSubtitleMatchesWithFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SearchSubtitleMatchesWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SearchVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosByTags(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideosByTags'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosWithFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SearchVideosWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SelectCollectionCover() {
  return window['go']['main']['App']['SelectCollectionCover']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFolderToRename() {
  return window['go']['main']['App']['SelectFolderToRename']();
}

export function SelectMigrationDestinationDirectory() {
  return window['go']['main']['App']['SelectMigrationDestinationDirectory']();
}

export function SelectMigrationSourceDirectory() {
  return window['go']['main']['App']['SelectMigrationSourceDirectory']();
}

export function SelectPersonAvatar() {
  return window['go']['main']['App']['SelectPersonAvatar']();
}

export function SetCollectionCover(arg1, arg2) {
  return window['go']['main']['App']['SetCollectionCover'](arg1, arg2);
}

export function SetPersonAvatar(arg1, arg2) {
  return window['go']['main']['App']['SetPersonAvatar'](arg1, arg2);
}

export function SetVideoFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetVideoFavorite'](arg1, arg2);
}

export function SetVideoWatched(arg1, arg2) {
  return window['go']['main']['App']['SetVideoWatched'](arg1, arg2);
}

export function StartCleanupAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCleanupAnalysis'](arg1, arg2, arg3);
}

export function StartLocalMetadataBackfill() {
  return window['go']['main']['App']['StartLocalMetadataBackfill']();
}

export function StartLocalMetadataExport(arg1) {
  return window['go']['main']['App']['StartLocalMetadataExport'](arg1);
}

export function StartPerceptualHashBackfill() {
  return window['go']['main']['App']['StartPerceptualHashBackfill']();
}

export function StartSemanticIndex(arg1) {
  return window['go']['main']['App']['StartSemanticIndex'](arg1);
}

export function StartTechnicalBackfill() {
  return window['go']['main']['App']['StartTechnicalBackfill']();
}

export function SyncScanDirectories() {
  return window['go']['main']['App']['SyncScanDirectories']();
}

export function TriggerAITagging() {
  return window['go']['main']['App']['TriggerAITagging']();
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDirectory'](arg1, arg2, arg3);
}

export function UpdatePerson(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePerson'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}

export function UpdateVideoDetails(arg1) {
  return window['go']['main']['App']['UpdateVideoDetails'](arg1);
}

export function UpdateVideoWatchProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVideoWatchProgress'](arg1, arg2, arg3);
}

export function ValidateSubtitleEditDocument(arg1) {
  return window['go']['main']['App']['ValidateSubtitleEditDocument'](arg1);
}

export function AddImageDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddImageDirectory'](arg1, arg2);
}

export function AddTagToImage(arg1, arg2) {
  return window['go']['main']['App']['AddTagToImage'](arg1, arg2);
}

export function BatchAddTagToImages(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToImages'](arg1, arg2);
}

export function BatchRemoveTagFromImages(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromImages'](arg1, arg2);
}

export function DeleteImageDirectory(arg1) {
  return window['go']['main']['App']['DeleteImageDirectory'](arg1);
}

export function GetAllImageDirectories() {
  return window['go']['main']['App']['GetAllImageDirectories']();
}

export function GetImageDetail(arg1) {
  return window['go']['main']['App']['GetImageDetail'](arg1);
}

export function GetImageInsights() {
  return window['go']['main']['App']['GetImageInsights']();
}

export function RemoveTagFromImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromImage'](arg1, arg2);
}

export function SearchImagePage(arg1) {
  return window['go']['main']['App']['SearchImagePage'](arg1);
}

export function SetImageFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetImageFavorite'](arg1, arg2);
}

export function SetImageRating(arg1, arg2) {
  return window['go']['main']['App']['SetImageRating'](arg1, arg2);
}

export function SyncImageDirectories() {
  return window['go']['main']['App']['SyncImageDirectories']();
}

export function UpdateImageDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateImageDirectory'](arg1, arg2, arg3);
}

export function BatchDeleteImages(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteImages'](arg1, arg2);
}

export function DeleteImage(arg1, arg2) {
  return window['go']['main']['App']['DeleteImage'](arg1, arg2);
}

export function ListImageTrashEntries() {
  return window['go']['main']['App']['ListImageTrashEntries']();
}

export function RestoreImageTrashEntry(arg1) {
  return window['go']['main']['App']['RestoreImageTrashEntry'](arg1);
}

export function CancelImageAIDescription() {
  return window['go']['main']['App']['CancelImageAIDescription']();
}

export function GetImageAIDescriptionStatus() {
  return window['go']['main']['App']['GetImageAIDescriptionStatus']();
}

export function RegenerateImageAIDescription(arg1) {
  return window['go']['main']['App']['RegenerateImageAIDescription'](arg1);
}

export function StartImageAIDescription() {
  return window['go']['main']['App']['StartImageAIDescription']();
}

export function CancelImageEXIFBackfill() {
  return window['go']['main']['App']['CancelImageEXIFBackfill']();
}

export function GetImageEXIFBackfillStatus() {
  return window['go']['main']['App']['GetImageEXIFBackfillStatus']();
}

export function StartImageEXIFBackfill() {
  return window['go']['main']['App']['StartImageEXIFBackfill']();
}

export function CancelImageSemanticIndex() {
  return window['go']['main']['App']['CancelImageSemanticIndex']();
}

export function DismissImageNearDuplicateGroup(arg1) {
  return window['go']['main']['App']['DismissImageNearDuplicateGroup'](arg1);
}

export function GetImageCleanupStatus() {
  return window['go']['main']['App']['GetImageCleanupStatus']();
}

export function GetImageSemanticIndexStatus() {
  return window['go']['main']['App']['GetImageSemanticIndexStatus']();
}

export function SearchImagesSemantic(arg1) {
  return window['go']['main']['App']['SearchImagesSemantic'](arg1);
}

export function StartImageCleanupAnalysis() {
  return window['go']['main']['App']['StartImageCleanupAnalysis']();
}

export function StartImageSemanticIndex() {
  return window['go']['main']['App']['StartImageSemanticIndex']();
}
