// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionVideo'](arg1, arg2);
}

export function AddCollectionVideos(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionVideos'](arg1, arg2);
}

export function AddDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2);
}

export function AddDownloadDirectoryToScan(arg1) {
  return window['go']['main']['App']['AddDownloadDirectoryToScan'](arg1);
}

export function AddImageDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddImageDirectory'](arg1, arg2);
}

export function AddPersonImages(arg1, arg2) {
  return window['go']['main']['App']['AddPersonImages'](arg1, arg2);
}

export function AddPersonVideo(arg1, arg2) {
  return window['go']['main']['App']['AddPersonVideo'](arg1, arg2);
}

export function AddPersonVideos(arg1, arg2) {
  return window['go']['main']['App']['AddPersonVideos'](arg1, arg2);
}

export function AddTagToImage(arg1, arg2) {
  return window['go']['main']['App']['AddTagToImage'](arg1, arg2);
}

export function AddTagToVideo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToVideo'](arg1, arg2);
}

export function ApplyLocalMetadataBatch(arg1) {
  return window['go']['main']['App']['ApplyLocalMetadataBatch'](arg1);
}

export function ApplyWatchlistCandidate(arg1, arg2) {
  return window['go']['main']['App']['ApplyWatchlistCandidate'](arg1, arg2);
}

export function ApproveAITagCandidate(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidate'](arg1);
}

export function ApproveAITagCandidates(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidates'](arg1);
}

export function ApproveAITagCandidatesByFilter(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidatesByFilter'](arg1);
}

export function ApproveImageAITagCandidate(arg1) {
  return window['go']['main']['App']['ApproveImageAITagCandidate'](arg1);
}

export function BatchAddTagToImages(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToImages'](arg1, arg2);
}

export function BatchAddTagToVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToVideos'](arg1, arg2);
}

export function BatchCreatePlaybackProxies(arg1) {
  return window['go']['main']['App']['BatchCreatePlaybackProxies'](arg1);
}

export function BatchCreatePlaybackProxiesForFilter(arg1) {
  return window['go']['main']['App']['BatchCreatePlaybackProxiesForFilter'](arg1);
}

export function BatchMoveVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchMoveVideos'](arg1, arg2);
}

export function BatchRemoveTagFromVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromVideos'](arg1, arg2);
}

export function CancelBatchDelete(arg1) {
  return window['go']['main']['App']['CancelBatchDelete'](arg1);
}

export function CancelBrowserDownloadTask(arg1) {
  return window['go']['main']['App']['CancelBrowserDownloadTask'](arg1);
}

export function CancelCleanupAnalysis() {
  return window['go']['main']['App']['CancelCleanupAnalysis']();
}

export function CancelCollectionSuggestionAnalysis() {
  return window['go']['main']['App']['CancelCollectionSuggestionAnalysis']();
}

export function CancelEnhancementModelDownload() {
  return window['go']['main']['App']['CancelEnhancementModelDownload']();
}

export function CancelEnhancementTask(arg1) {
  return window['go']['main']['App']['CancelEnhancementTask'](arg1);
}

export function CancelFaceAnalysis() {
  return window['go']['main']['App']['CancelFaceAnalysis']();
}

export function CancelFaceRuntimePrepare() {
  return window['go']['main']['App']['CancelFaceRuntimePrepare']();
}

export function CancelFrameHashBackfill() {
  return window['go']['main']['App']['CancelFrameHashBackfill']();
}

export function CancelImageAITagging() {
  return window['go']['main']['App']['CancelImageAITagging']();
}

export function CancelImageCleanupAnalysis() {
  return window['go']['main']['App']['CancelImageCleanupAnalysis']();
}

export function CancelImageEXIFBackfill() {
  return window['go']['main']['App']['CancelImageEXIFBackfill']();
}

export function CancelImagePerceptualHashBackfill() {
  return window['go']['main']['App']['CancelImagePerceptualHashBackfill']();
}

export function CancelImageSemanticIndex() {
  return window['go']['main']['App']['CancelImageSemanticIndex']();
}

export function CancelLocalMetadataBackfill() {
  return window['go']['main']['App']['CancelLocalMetadataBackfill']();
}

export function CancelLocalMetadataExport() {
  return window['go']['main']['App']['CancelLocalMetadataExport']();
}

export function CancelMovieChartRefresh() {
  return window['go']['main']['App']['CancelMovieChartRefresh']();
}

export function CancelPerceptualHashBackfill() {
  return window['go']['main']['App']['CancelPerceptualHashBackfill']();
}

export function CancelPlaybackProxyTask() {
  return window['go']['main']['App']['CancelPlaybackProxyTask']();
}

export function CancelSemanticIndex() {
  return window['go']['main']['App']['CancelSemanticIndex']();
}

export function CancelSubtitle() {
  return window['go']['main']['App']['CancelSubtitle']();
}

export function CancelSubtitleEnginePreparation() {
  return window['go']['main']['App']['CancelSubtitleEnginePreparation']();
}

export function CancelSubtitleTask(arg1) {
  return window['go']['main']['App']['CancelSubtitleTask'](arg1);
}

export function CancelSubtitleTranslation(arg1) {
  return window['go']['main']['App']['CancelSubtitleTranslation'](arg1);
}

export function CancelTechnicalBackfill() {
  return window['go']['main']['App']['CancelTechnicalBackfill']();
}

export function CheckMoveTarget(arg1) {
  return window['go']['main']['App']['CheckMoveTarget'](arg1);
}

export function ClearFaceData() {
  return window['go']['main']['App']['ClearFaceData']();
}

export function ClearMigrationTarget(arg1, arg2) {
  return window['go']['main']['App']['ClearMigrationTarget'](arg1, arg2);
}

export function ClearMovieChartMark(arg1) {
  return window['go']['main']['App']['ClearMovieChartMark'](arg1);
}

export function ClearPlaybackProxies() {
  return window['go']['main']['App']['ClearPlaybackProxies']();
}

export function ClearShortFeedPIN() {
  return window['go']['main']['App']['ClearShortFeedPIN']();
}

export function ClearVideoAutomaticTagOverride(arg1, arg2) {
  return window['go']['main']['App']['ClearVideoAutomaticTagOverride'](arg1, arg2);
}

export function ConfigureJellyfin(arg1) {
  return window['go']['main']['App']['ConfigureJellyfin'](arg1);
}

export function ConfirmCollectionSuggestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmCollectionSuggestion'](arg1, arg2, arg3);
}

export function ConfirmFaceClusterAppend(arg1) {
  return window['go']['main']['App']['ConfirmFaceClusterAppend'](arg1);
}

export function ConfirmFaceClusterAppendObservations(arg1, arg2) {
  return window['go']['main']['App']['ConfirmFaceClusterAppendObservations'](arg1, arg2);
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function ConfirmSameSourceRelation(arg1) {
  return window['go']['main']['App']['ConfirmSameSourceRelation'](arg1);
}

export function ConvertSubtitleToUTF8(arg1, arg2) {
  return window['go']['main']['App']['ConvertSubtitleToUTF8'](arg1, arg2);
}

export function ConvertTagToPerson(arg1) {
  return window['go']['main']['App']['ConvertTagToPerson'](arg1);
}

export function CountAITagCandidatesByFilter(arg1) {
  return window['go']['main']['App']['CountAITagCandidatesByFilter'](arg1);
}

export function CountLibraryVideos(arg1) {
  return window['go']['main']['App']['CountLibraryVideos'](arg1);
}

export function CreateBlankSubtitleDocument(arg1) {
  return window['go']['main']['App']['CreateBlankSubtitleDocument'](arg1);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateDatabaseBackup() {
  return window['go']['main']['App']['CreateDatabaseBackup']();
}

export function CreateEnhancementTask(arg1) {
  return window['go']['main']['App']['CreateEnhancementTask'](arg1);
}

export function CreatePerson(arg1, arg2) {
  return window['go']['main']['App']['CreatePerson'](arg1, arg2);
}

export function CreatePlaybackProxy(arg1) {
  return window['go']['main']['App']['CreatePlaybackProxy'](arg1);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function CreateTagCategory(arg1, arg2) {
  return window['go']['main']['App']['CreateTagCategory'](arg1, arg2);
}

export function CreateTagWithCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTagWithCategory'](arg1, arg2, arg3);
}

export function CreateWatchlistEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateWatchlistEntry'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteGlossaryEntry(arg1) {
  return window['go']['main']['App']['DeleteGlossaryEntry'](arg1);
}

export function DeleteImageDirectory(arg1) {
  return window['go']['main']['App']['DeleteImageDirectory'](arg1);
}

export function DeleteImagesInDirectoryWithResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteImagesInDirectoryWithResult'](arg1, arg2, arg3);
}

export function DeleteImagesWithResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteImagesWithResult'](arg1, arg2, arg3);
}

export function DeletePerson(arg1) {
  return window['go']['main']['App']['DeletePerson'](arg1);
}

export function DeletePlaybackProxy(arg1) {
  return window['go']['main']['App']['DeletePlaybackProxy'](arg1);
}

export function DeleteSavedLibraryView(arg1) {
  return window['go']['main']['App']['DeleteSavedLibraryView'](arg1);
}

export function DeleteStagedSources(arg1) {
  return window['go']['main']['App']['DeleteStagedSources'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTagCategory(arg1) {
  return window['go']['main']['App']['DeleteTagCategory'](arg1);
}

export function DeleteVideosWithResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteVideosWithResult'](arg1, arg2, arg3);
}

export function DeleteWatchlistEntry(arg1) {
  return window['go']['main']['App']['DeleteWatchlistEntry'](arg1);
}

export function DiscardEnhancementProgress(arg1) {
  return window['go']['main']['App']['DiscardEnhancementProgress'](arg1);
}

export function DiscardPendingSubtitle(arg1) {
  return window['go']['main']['App']['DiscardPendingSubtitle'](arg1);
}

export function DismissCleanupVideo(arg1, arg2) {
  return window['go']['main']['App']['DismissCleanupVideo'](arg1, arg2);
}

export function DismissClipCandidate(arg1, arg2) {
  return window['go']['main']['App']['DismissClipCandidate'](arg1, arg2);
}

export function DismissCollectionSuggestion(arg1) {
  return window['go']['main']['App']['DismissCollectionSuggestion'](arg1);
}

export function DismissFaceClusterAppend(arg1) {
  return window['go']['main']['App']['DismissFaceClusterAppend'](arg1);
}

export function DismissImageNearDuplicateGroup(arg1) {
  return window['go']['main']['App']['DismissImageNearDuplicateGroup'](arg1);
}

export function DismissImageNearDuplicateMember(arg1, arg2) {
  return window['go']['main']['App']['DismissImageNearDuplicateMember'](arg1, arg2);
}

export function DismissInterruptedSubtitleJobs() {
  return window['go']['main']['App']['DismissInterruptedSubtitleJobs']();
}

export function DismissNearDuplicateGroup(arg1) {
  return window['go']['main']['App']['DismissNearDuplicateGroup'](arg1);
}

export function DismissNearDuplicateMember(arg1, arg2) {
  return window['go']['main']['App']['DismissNearDuplicateMember'](arg1, arg2);
}

export function EnforcePlaybackProxyLimit() {
  return window['go']['main']['App']['EnforcePlaybackProxyLimit']();
}

export function ExportLocalMetadataNFO(arg1) {
  return window['go']['main']['App']['ExportLocalMetadataNFO'](arg1);
}

export function FilterActivePersonIDs(arg1) {
  return window['go']['main']['App']['FilterActivePersonIDs'](arg1);
}

export function FilterActiveTagIDs(arg1) {
  return window['go']['main']['App']['FilterActiveTagIDs'](arg1);
}

export function FindSimilarVideos(arg1) {
  return window['go']['main']['App']['FindSimilarVideos'](arg1);
}

export function ForceGenerateSubtitle(arg1) {
  return window['go']['main']['App']['ForceGenerateSubtitle'](arg1);
}

export function ForceRemoveTrashRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForceRemoveTrashRecords'](arg1, arg2, arg3);
}

export function GenerateSubtitle(arg1) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1);
}

export function GetAIQualityReport(arg1) {
  return window['go']['main']['App']['GetAIQualityReport'](arg1);
}

export function GetAITaggingStatusSummary() {
  return window['go']['main']['App']['GetAITaggingStatusSummary']();
}

export function GetAllDirectories() {
  return window['go']['main']['App']['GetAllDirectories']();
}

export function GetAllImageDirectories() {
  return window['go']['main']['App']['GetAllImageDirectories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAutomaticOverrideKinds(arg1) {
  return window['go']['main']['App']['GetAutomaticOverrideKinds'](arg1);
}

export function GetBackgroundTasks() {
  return window['go']['main']['App']['GetBackgroundTasks']();
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetBrowserBridgeStatus() {
  return window['go']['main']['App']['GetBrowserBridgeStatus']();
}

export function GetCleanupStatus() {
  return window['go']['main']['App']['GetCleanupStatus']();
}

export function GetCollectionDetail(arg1) {
  return window['go']['main']['App']['GetCollectionDetail'](arg1);
}

export function GetCollectionSuggestionStatus() {
  return window['go']['main']['App']['GetCollectionSuggestionStatus']();
}

export function GetDatabaseBackendStatus() {
  return window['go']['main']['App']['GetDatabaseBackendStatus']();
}

export function GetDatabaseSwitchStatus() {
  return window['go']['main']['App']['GetDatabaseSwitchStatus']();
}

export function GetEnhancementCapability() {
  return window['go']['main']['App']['GetEnhancementCapability']();
}

export function GetEnhancementModelStatus() {
  return window['go']['main']['App']['GetEnhancementModelStatus']();
}

export function GetEnhancementVideoPreflight(arg1) {
  return window['go']['main']['App']['GetEnhancementVideoPreflight'](arg1);
}

export function GetFaceAnalysisStatus() {
  return window['go']['main']['App']['GetFaceAnalysisStatus']();
}

export function GetFaceClusterObservations(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFaceClusterObservations'](arg1, arg2, arg3);
}

export function GetFaceDataUsage() {
  return window['go']['main']['App']['GetFaceDataUsage']();
}

export function GetFaceRuntimeStatus() {
  return window['go']['main']['App']['GetFaceRuntimeStatus']();
}

export function GetFrameHashBackfillStatus() {
  return window['go']['main']['App']['GetFrameHashBackfillStatus']();
}

export function GetIINASyncStatus() {
  return window['go']['main']['App']['GetIINASyncStatus']();
}

export function GetIdleSchedulerStatus() {
  return window['go']['main']['App']['GetIdleSchedulerStatus']();
}

export function GetImageAITaggingStatus() {
  return window['go']['main']['App']['GetImageAITaggingStatus']();
}

export function GetImageAITaggingSummary() {
  return window['go']['main']['App']['GetImageAITaggingSummary']();
}

export function GetImageCleanupStatus() {
  return window['go']['main']['App']['GetImageCleanupStatus']();
}

export function GetImageDetail(arg1) {
  return window['go']['main']['App']['GetImageDetail'](arg1);
}

export function GetImageEXIFBackfillStatus() {
  return window['go']['main']['App']['GetImageEXIFBackfillStatus']();
}

export function GetImageInsights() {
  return window['go']['main']['App']['GetImageInsights']();
}

export function GetImagePerceptualHashBackfillStatus() {
  return window['go']['main']['App']['GetImagePerceptualHashBackfillStatus']();
}

export function GetImageSemanticIndexStatus() {
  return window['go']['main']['App']['GetImageSemanticIndexStatus']();
}

export function GetImageTags() {
  return window['go']['main']['App']['GetImageTags']();
}

export function GetInterruptedSubtitleJobs() {
  return window['go']['main']['App']['GetInterruptedSubtitleJobs']();
}

export function GetJellyfinDiagnostics() {
  return window['go']['main']['App']['GetJellyfinDiagnostics']();
}

export function GetJellyfinStatus() {
  return window['go']['main']['App']['GetJellyfinStatus']();
}

export function GetLibraryCounts() {
  return window['go']['main']['App']['GetLibraryCounts']();
}

export function GetLibraryInsights() {
  return window['go']['main']['App']['GetLibraryInsights']();
}

export function GetLibrarySubtitleHits(arg1, arg2) {
  return window['go']['main']['App']['GetLibrarySubtitleHits'](arg1, arg2);
}

export function GetLibraryWatcherStatus() {
  return window['go']['main']['App']['GetLibraryWatcherStatus']();
}

export function GetLocalMetadataBackfillStatus() {
  return window['go']['main']['App']['GetLocalMetadataBackfillStatus']();
}

export function GetLocalMetadataExportStatus() {
  return window['go']['main']['App']['GetLocalMetadataExportStatus']();
}

export function GetPendingWorkSummary() {
  return window['go']['main']['App']['GetPendingWorkSummary']();
}

export function GetPerceptualHashBackfillStatus() {
  return window['go']['main']['App']['GetPerceptualHashBackfillStatus']();
}

export function GetPersonDeletionImpact(arg1) {
  return window['go']['main']['App']['GetPersonDeletionImpact'](arg1);
}

export function GetPersonDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPersonDetail'](arg1, arg2, arg3);
}

export function GetPersonImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPersonImages'](arg1, arg2, arg3);
}

export function GetPlaybackProxy(arg1) {
  return window['go']['main']['App']['GetPlaybackProxy'](arg1);
}

export function GetPlaybackProxyStatus() {
  return window['go']['main']['App']['GetPlaybackProxyStatus']();
}

export function GetPlaybackProxyUsage() {
  return window['go']['main']['App']['GetPlaybackProxyUsage']();
}

export function GetPreviewSession(arg1) {
  return window['go']['main']['App']['GetPreviewSession'](arg1);
}

export function GetSemanticIndexStatus() {
  return window['go']['main']['App']['GetSemanticIndexStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShortFeedAccessStatus() {
  return window['go']['main']['App']['GetShortFeedAccessStatus']();
}

export function GetShortFeedQRCode() {
  return window['go']['main']['App']['GetShortFeedQRCode']();
}

export function GetShortFeedServerStatus() {
  return window['go']['main']['App']['GetShortFeedServerStatus']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetSubtitleEditDocument(arg1) {
  return window['go']['main']['App']['GetSubtitleEditDocument'](arg1);
}

export function GetSubtitleEngineStatuses() {
  return window['go']['main']['App']['GetSubtitleEngineStatuses']();
}

export function GetSubtitleIndexSyncStatus() {
  return window['go']['main']['App']['GetSubtitleIndexSyncStatus']();
}

export function GetSubtitleOverwriteInfo(arg1) {
  return window['go']['main']['App']['GetSubtitleOverwriteInfo'](arg1);
}

export function GetSubtitleQueueState() {
  return window['go']['main']['App']['GetSubtitleQueueState']();
}

export function GetSubtitleSegments(arg1) {
  return window['go']['main']['App']['GetSubtitleSegments'](arg1);
}

export function GetTagUsageCounts(arg1) {
  return window['go']['main']['App']['GetTagUsageCounts'](arg1);
}

export function GetTaskCenterSnapshot() {
  return window['go']['main']['App']['GetTaskCenterSnapshot']();
}

export function GetTechnicalBackfillStatus() {
  return window['go']['main']['App']['GetTechnicalBackfillStatus']();
}

export function GetTrashUsage() {
  return window['go']['main']['App']['GetTrashUsage']();
}

export function GetVideoAutomaticTagOverrides(arg1) {
  return window['go']['main']['App']['GetVideoAutomaticTagOverrides'](arg1);
}

export function GetVideoDetails(arg1) {
  return window['go']['main']['App']['GetVideoDetails'](arg1);
}

export function GetVideosByIDs(arg1) {
  return window['go']['main']['App']['GetVideosByIDs'](arg1);
}

export function GetWallpaperPreflight(arg1, arg2) {
  return window['go']['main']['App']['GetWallpaperPreflight'](arg1, arg2);
}

export function GetWallpaperStatus() {
  return window['go']['main']['App']['GetWallpaperStatus']();
}

export function IgnoreFaceCluster(arg1) {
  return window['go']['main']['App']['IgnoreFaceCluster'](arg1);
}

export function LinkFaceCluster(arg1, arg2) {
  return window['go']['main']['App']['LinkFaceCluster'](arg1, arg2);
}

export function LinkMovieToVideo(arg1, arg2) {
  return window['go']['main']['App']['LinkMovieToVideo'](arg1, arg2);
}

export function ListAITagCandidatePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListAITagCandidatePage'](arg1, arg2, arg3, arg4, arg5);
}

export function ListCleanupDismissals(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCleanupDismissals'](arg1, arg2, arg3);
}

export function ListCollectionSuggestions() {
  return window['go']['main']['App']['ListCollectionSuggestions']();
}

export function ListCollections(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListCollections'](arg1, arg2, arg3, arg4);
}

export function ListContinueWatchingWithFilter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListContinueWatchingWithFilter'](arg1, arg2, arg3, arg4);
}

export function ListDatabaseBackups() {
  return window['go']['main']['App']['ListDatabaseBackups']();
}

export function ListDownloadTasks() {
  return window['go']['main']['App']['ListDownloadTasks']();
}

export function ListEnhancementTasks(arg1) {
  return window['go']['main']['App']['ListEnhancementTasks'](arg1);
}

export function ListFaceClusterPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFaceClusterPage'](arg1, arg2, arg3);
}

export function ListGlossaryEntries(arg1) {
  return window['go']['main']['App']['ListGlossaryEntries'](arg1);
}

export function ListHiddenImages(arg1, arg2) {
  return window['go']['main']['App']['ListHiddenImages'](arg1, arg2);
}

export function ListIgnoredFaceClusters(arg1, arg2) {
  return window['go']['main']['App']['ListIgnoredFaceClusters'](arg1, arg2);
}

export function ListImageAITagCandidatePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListImageAITagCandidatePage'](arg1, arg2, arg3, arg4, arg5);
}

export function ListImageAITagCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListImageAITagCandidates'](arg1, arg2, arg3);
}

export function ListImageFolderGroups(arg1) {
  return window['go']['main']['App']['ListImageFolderGroups'](arg1);
}

export function ListImageTimelineBuckets(arg1) {
  return window['go']['main']['App']['ListImageTimelineBuckets'](arg1);
}

export function ListMovieChart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListMovieChart'](arg1, arg2, arg3, arg4);
}

export function ListMovieChartYears() {
  return window['go']['main']['App']['ListMovieChartYears']();
}

export function ListMovieVideoLinks(arg1) {
  return window['go']['main']['App']['ListMovieVideoLinks'](arg1);
}

export function ListPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPeople'](arg1, arg2, arg3, arg4);
}

export function ListRecentlyPlayedWithFilter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRecentlyPlayedWithFilter'](arg1, arg2, arg3, arg4);
}

export function ListSameSourceRelations(arg1, arg2) {
  return window['go']['main']['App']['ListSameSourceRelations'](arg1, arg2);
}

export function ListSavedLibraryViews() {
  return window['go']['main']['App']['ListSavedLibraryViews']();
}

export function ListStagedSources() {
  return window['go']['main']['App']['ListStagedSources']();
}

export function ListStaleReasonCounts() {
  return window['go']['main']['App']['ListStaleReasonCounts']();
}

export function ListSubtitleBackups(arg1) {
  return window['go']['main']['App']['ListSubtitleBackups'](arg1);
}

export function ListTagPersonConversions(arg1) {
  return window['go']['main']['App']['ListTagPersonConversions'](arg1);
}

export function ListTrashEntries(arg1) {
  return window['go']['main']['App']['ListTrashEntries'](arg1);
}

export function ListWatchedMovies() {
  return window['go']['main']['App']['ListWatchedMovies']();
}

export function ListWatchlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListWatchlist'](arg1, arg2, arg3);
}

export function ListWatchlistCandidates(arg1) {
  return window['go']['main']['App']['ListWatchlistCandidates'](arg1);
}

export function LogFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3);
}

export function MarkMovieChartEntry(arg1, arg2) {
  return window['go']['main']['App']['MarkMovieChartEntry'](arg1, arg2);
}

export function MarkSameSourceRelationRead(arg1) {
  return window['go']['main']['App']['MarkSameSourceRelationRead'](arg1);
}

export function MergeMediaMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeMediaMetadata'](arg1, arg2, arg3, arg4);
}

export function MergePeople(arg1, arg2) {
  return window['go']['main']['App']['MergePeople'](arg1, arg2);
}

export function MergeTags(arg1, arg2) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2);
}

export function MoveDirectory(arg1, arg2) {
  return window['go']['main']['App']['MoveDirectory'](arg1, arg2);
}

export function MoveVideo(arg1, arg2) {
  return window['go']['main']['App']['MoveVideo'](arg1, arg2);
}

export function NameFaceCluster(arg1, arg2, arg3) {
  return window['go']['main']['App']['NameFaceCluster'](arg1, arg2, arg3);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenImageDirectory(arg1) {
  return window['go']['main']['App']['OpenImageDirectory'](arg1);
}

export function OpenMovieChartYear(arg1) {
  return window['go']['main']['App']['OpenMovieChartYear'](arg1);
}

export function PermanentlyDeleteImages(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteImages'](arg1);
}

export function PermanentlyDeleteVideos(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteVideos'](arg1);
}

export function PickRandomVideos(arg1, arg2) {
  return window['go']['main']['App']['PickRandomVideos'](arg1, arg2);
}

export function PlayRandomVideoWithFilter(arg1) {
  return window['go']['main']['App']['PlayRandomVideoWithFilter'](arg1);
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function PreflightDatabaseSwitch(arg1) {
  return window['go']['main']['App']['PreflightDatabaseSwitch'](arg1);
}

export function PrepareFaceRuntime() {
  return window['go']['main']['App']['PrepareFaceRuntime']();
}

export function PrepareSubtitleEngine(arg1) {
  return window['go']['main']['App']['PrepareSubtitleEngine'](arg1);
}

export function PreviewExternally(arg1) {
  return window['go']['main']['App']['PreviewExternally'](arg1);
}

export function PreviewFaceClusterUnlink(arg1) {
  return window['go']['main']['App']['PreviewFaceClusterUnlink'](arg1);
}

export function PreviewLocalMetadataBatch(arg1) {
  return window['go']['main']['App']['PreviewLocalMetadataBatch'](arg1);
}

export function PreviewTagPersonConversion(arg1) {
  return window['go']['main']['App']['PreviewTagPersonConversion'](arg1);
}

export function PurgeTrashEntries(arg1, arg2) {
  return window['go']['main']['App']['PurgeTrashEntries'](arg1, arg2);
}

export function ReaddRemovedRoot(arg1) {
  return window['go']['main']['App']['ReaddRemovedRoot'](arg1);
}

export function ReassignFaceCluster(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReassignFaceCluster'](arg1, arg2, arg3);
}

export function RecheckImages(arg1) {
  return window['go']['main']['App']['RecheckImages'](arg1);
}

export function RecheckVideos(arg1) {
  return window['go']['main']['App']['RecheckVideos'](arg1);
}

export function RecordViewEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordViewEvent'](arg1, arg2, arg3);
}

export function RefreshMovieChart(arg1) {
  return window['go']['main']['App']['RefreshMovieChart'](arg1);
}

export function RefreshVideoTechnicalMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoTechnicalMetadata'](arg1);
}

export function RegenerateBrowserBridgeToken() {
  return window['go']['main']['App']['RegenerateBrowserBridgeToken']();
}

export function ReimportDownload(arg1) {
  return window['go']['main']['App']['ReimportDownload'](arg1);
}

export function RejectAITagCandidate(arg1) {
  return window['go']['main']['App']['RejectAITagCandidate'](arg1);
}

export function RejectAITagCandidatesByVideo(arg1) {
  return window['go']['main']['App']['RejectAITagCandidatesByVideo'](arg1);
}

export function RejectImageAITagCandidate(arg1) {
  return window['go']['main']['App']['RejectImageAITagCandidate'](arg1);
}

export function RejectImageAITagCandidatesByImage(arg1) {
  return window['go']['main']['App']['RejectImageAITagCandidatesByImage'](arg1);
}

export function RejectSameSourceRelation(arg1) {
  return window['go']['main']['App']['RejectSameSourceRelation'](arg1);
}

export function RelaunchApp() {
  return window['go']['main']['App']['RelaunchApp']();
}

export function RelocateVideo(arg1, arg2) {
  return window['go']['main']['App']['RelocateVideo'](arg1, arg2);
}

export function RemoveCollectionCover(arg1) {
  return window['go']['main']['App']['RemoveCollectionCover'](arg1);
}

export function RemoveCollectionVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveCollectionVideo'](arg1, arg2);
}

export function RemoveFaceClusterObservation(arg1, arg2) {
  return window['go']['main']['App']['RemoveFaceClusterObservation'](arg1, arg2);
}

export function RemoveGoneTrashEntries(arg1, arg2) {
  return window['go']['main']['App']['RemoveGoneTrashEntries'](arg1, arg2);
}

export function RemovePersonAvatar(arg1) {
  return window['go']['main']['App']['RemovePersonAvatar'](arg1);
}

export function RemovePersonImage(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonImage'](arg1, arg2);
}

export function RemovePersonVideo(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonVideo'](arg1, arg2);
}

export function RemoveTagFromImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromImage'](arg1, arg2);
}

export function RemoveTagFromVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromVideo'](arg1, arg2);
}

export function RenameDirectory(arg1, arg2) {
  return window['go']['main']['App']['RenameDirectory'](arg1, arg2);
}

export function RenameTagCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameTagCategory'](arg1, arg2);
}

export function RenameVideo(arg1, arg2) {
  return window['go']['main']['App']['RenameVideo'](arg1, arg2);
}

export function ReorderCollectionVideos(arg1, arg2) {
  return window['go']['main']['App']['ReorderCollectionVideos'](arg1, arg2);
}

export function RequeueInterruptedSubtitleJobs() {
  return window['go']['main']['App']['RequeueInterruptedSubtitleJobs']();
}

export function RerollRandom(arg1) {
  return window['go']['main']['App']['RerollRandom'](arg1);
}

export function ResolveSubtitleJob(arg1, arg2) {
  return window['go']['main']['App']['ResolveSubtitleJob'](arg1, arg2);
}

export function RestoreDatabaseBackup(arg1) {
  return window['go']['main']['App']['RestoreDatabaseBackup'](arg1);
}

export function RestoreFaceCluster(arg1) {
  return window['go']['main']['App']['RestoreFaceCluster'](arg1);
}

export function RestoreSubtitleBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreSubtitleBackup'](arg1, arg2);
}

export function RestoreTrashBatch(arg1, arg2) {
  return window['go']['main']['App']['RestoreTrashBatch'](arg1, arg2);
}

export function RestoreTrashEntries(arg1, arg2) {
  return window['go']['main']['App']['RestoreTrashEntries'](arg1, arg2);
}

export function RetranslateSubtitleEntries(arg1) {
  return window['go']['main']['App']['RetranslateSubtitleEntries'](arg1);
}

export function RetryAITagging(arg1) {
  return window['go']['main']['App']['RetryAITagging'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function RetryEnhancementTask(arg1) {
  return window['go']['main']['App']['RetryEnhancementTask'](arg1);
}

export function RetryImageAITagging(arg1) {
  return window['go']['main']['App']['RetryImageAITagging'](arg1);
}

export function RetryLibraryWatcherRoot(arg1) {
  return window['go']['main']['App']['RetryLibraryWatcherRoot'](arg1);
}

export function RetryWatchlistEnrichment(arg1) {
  return window['go']['main']['App']['RetryWatchlistEnrichment'](arg1);
}

export function RevealBackupDirectory() {
  return window['go']['main']['App']['RevealBackupDirectory']();
}

export function RevealDownload(arg1) {
  return window['go']['main']['App']['RevealDownload'](arg1);
}

export function RevealImage(arg1) {
  return window['go']['main']['App']['RevealImage'](arg1);
}

export function RunGatedTaskNow(arg1) {
  return window['go']['main']['App']['RunGatedTaskNow'](arg1);
}

export function SaveLibraryView(arg1) {
  return window['go']['main']['App']['SaveLibraryView'](arg1);
}

export function SaveSubtitleEditDocument(arg1) {
  return window['go']['main']['App']['SaveSubtitleEditDocument'](arg1);
}

export function SearchImagePage(arg1) {
  return window['go']['main']['App']['SearchImagePage'](arg1);
}

export function SearchImagesSemantic(arg1) {
  return window['go']['main']['App']['SearchImagesSemantic'](arg1);
}

export function SearchLibraryVideoPage(arg1) {
  return window['go']['main']['App']['SearchLibraryVideoPage'](arg1);
}

export function SearchSemanticVideos(arg1) {
  return window['go']['main']['App']['SearchSemanticVideos'](arg1);
}

export function SelectBrowserDownloadDirectory() {
  return window['go']['main']['App']['SelectBrowserDownloadDirectory']();
}

export function SelectCollectionCover() {
  return window['go']['main']['App']['SelectCollectionCover']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFolderToRename() {
  return window['go']['main']['App']['SelectFolderToRename']();
}

export function SelectMigrationDestinationDirectory() {
  return window['go']['main']['App']['SelectMigrationDestinationDirectory']();
}

export function SelectMigrationSourceDirectory() {
  return window['go']['main']['App']['SelectMigrationSourceDirectory']();
}

export function SelectPersonAvatar() {
  return window['go']['main']['App']['SelectPersonAvatar']();
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function SetCollectionCover(arg1, arg2) {
  return window['go']['main']['App']['SetCollectionCover'](arg1, arg2);
}

export function SetImageFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetImageFavorite'](arg1, arg2);
}

export function SetImageRating(arg1, arg2) {
  return window['go']['main']['App']['SetImageRating'](arg1, arg2);
}

export function SetPersonAvatar(arg1, arg2) {
  return window['go']['main']['App']['SetPersonAvatar'](arg1, arg2);
}

export function SetShortFeedEnabled(arg1) {
  return window['go']['main']['App']['SetShortFeedEnabled'](arg1);
}

export function SetShortFeedPIN(arg1) {
  return window['go']['main']['App']['SetShortFeedPIN'](arg1);
}

export function SetVideoFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetVideoFavorite'](arg1, arg2);
}

export function SetVideoLiked(arg1, arg2) {
  return window['go']['main']['App']['SetVideoLiked'](arg1, arg2);
}

export function SetVideoWatched(arg1, arg2) {
  return window['go']['main']['App']['SetVideoWatched'](arg1, arg2);
}

export function SetWallpaper(arg1, arg2) {
  return window['go']['main']['App']['SetWallpaper'](arg1, arg2);
}

export function SetWindowForeground(arg1) {
  return window['go']['main']['App']['SetWindowForeground'](arg1);
}

export function StartCleanupAnalysisFromSettings() {
  return window['go']['main']['App']['StartCleanupAnalysisFromSettings']();
}

export function StartCollectionSuggestionAnalysis() {
  return window['go']['main']['App']['StartCollectionSuggestionAnalysis']();
}

export function StartDatabaseSwitch(arg1) {
  return window['go']['main']['App']['StartDatabaseSwitch'](arg1);
}

export function StartEnhancementModelDownload() {
  return window['go']['main']['App']['StartEnhancementModelDownload']();
}

export function StartFaceAnalysis(arg1) {
  return window['go']['main']['App']['StartFaceAnalysis'](arg1);
}

export function StartFrameHashBackfill() {
  return window['go']['main']['App']['StartFrameHashBackfill']();
}

export function StartImageAITagging() {
  return window['go']['main']['App']['StartImageAITagging']();
}

export function StartImageCleanupAnalysis() {
  return window['go']['main']['App']['StartImageCleanupAnalysis']();
}

export function StartImageEXIFBackfill() {
  return window['go']['main']['App']['StartImageEXIFBackfill']();
}

export function StartImagePerceptualHashBackfill() {
  return window['go']['main']['App']['StartImagePerceptualHashBackfill']();
}

export function StartImageSemanticIndex() {
  return window['go']['main']['App']['StartImageSemanticIndex']();
}

export function StartLocalMetadataBackfill() {
  return window['go']['main']['App']['StartLocalMetadataBackfill']();
}

export function StartLocalMetadataExport(arg1) {
  return window['go']['main']['App']['StartLocalMetadataExport'](arg1);
}

export function StartPerceptualHashBackfill() {
  return window['go']['main']['App']['StartPerceptualHashBackfill']();
}

export function StartSemanticIndex(arg1) {
  return window['go']['main']['App']['StartSemanticIndex'](arg1);
}

export function StartTechnicalBackfill() {
  return window['go']['main']['App']['StartTechnicalBackfill']();
}

export function StopVideoWallpaper() {
  return window['go']['main']['App']['StopVideoWallpaper']();
}

export function SuggestLibraryMatchesBatch(arg1) {
  return window['go']['main']['App']['SuggestLibraryMatchesBatch'](arg1);
}

export function SwitchBackendConfigOnly(arg1) {
  return window['go']['main']['App']['SwitchBackendConfigOnly'](arg1);
}

export function SyncDirectoryWithProgress(arg1, arg2) {
  return window['go']['main']['App']['SyncDirectoryWithProgress'](arg1, arg2);
}

export function SyncImageDirectories() {
  return window['go']['main']['App']['SyncImageDirectories']();
}

export function SyncScanDirectories(arg1) {
  return window['go']['main']['App']['SyncScanDirectories'](arg1);
}

export function SyncSubtitleIndexNow() {
  return window['go']['main']['App']['SyncSubtitleIndexNow']();
}

export function TestAITaggingConnection(arg1) {
  return window['go']['main']['App']['TestAITaggingConnection'](arg1);
}

export function TestWatchlistMetadataConnection(arg1) {
  return window['go']['main']['App']['TestWatchlistMetadataConnection'](arg1);
}

export function TranslateSubtitle(arg1) {
  return window['go']['main']['App']['TranslateSubtitle'](arg1);
}

export function TrashStagedSources(arg1) {
  return window['go']['main']['App']['TrashStagedSources'](arg1);
}

export function TriggerAITagging() {
  return window['go']['main']['App']['TriggerAITagging']();
}

export function UndoCleanupDismissals(arg1, arg2) {
  return window['go']['main']['App']['UndoCleanupDismissals'](arg1, arg2);
}

export function UndoTagPersonConversion(arg1) {
  return window['go']['main']['App']['UndoTagPersonConversion'](arg1);
}

export function UnlinkFaceCluster(arg1, arg2) {
  return window['go']['main']['App']['UnlinkFaceCluster'](arg1, arg2);
}

export function UnlinkMovieVideo(arg1, arg2) {
  return window['go']['main']['App']['UnlinkMovieVideo'](arg1, arg2);
}

export function UnlockShortFeedLogin() {
  return window['go']['main']['App']['UnlockShortFeedLogin']();
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateDirectoryWithMode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateDirectoryWithMode'](arg1, arg2, arg3, arg4);
}

export function UpdateImageDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateImageDirectory'](arg1, arg2, arg3);
}

export function UpdatePerson(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePerson'](arg1, arg2, arg3);
}

export function UpdateSavedLibraryView(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedLibraryView'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTagWithCategory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTagWithCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateVideoDetails(arg1) {
  return window['go']['main']['App']['UpdateVideoDetails'](arg1);
}

export function UpdateVideoRating(arg1, arg2) {
  return window['go']['main']['App']['UpdateVideoRating'](arg1, arg2);
}

export function UpdateVideoWatchProgress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateVideoWatchProgress'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateWatchlistEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateWatchlistEntry'](arg1, arg2);
}

export function UpsertGlossaryEntry(arg1) {
  return window['go']['main']['App']['UpsertGlossaryEntry'](arg1);
}

export function ValidateScanDirectory(arg1) {
  return window['go']['main']['App']['ValidateScanDirectory'](arg1);
}
