package models

func AllModels() []interface{} {
	return []interface{}{
		&Video{},
		&VideoTrashEntry{},
		&SubtitleSegment{},
		&SubtitleIndexState{},
		&Tag{},
		&AITaggingRun{},
		&AITagCandidate{},
		&AITagApprovalRecord{},
		&AITaggingState{},
		&AITagAgentStep{},
		&VideoVisualFingerprint{},
		&VideoSameSourceRelation{},
		&AISameSourceEvaluation{},
		&ShortFeedInteraction{},
		&ShortFeedImageInteraction{},
		&ShortFeedTagPreference{},
		&Settings{},
		&ScanDirectory{},
		&SavedLibraryView{},
		&Person{},
		&VideoPerson{},
		&MediaCollection{},
		&CollectionVideo{},
		&VideoLocalMetadataState{},
		&VideoTechnicalMetadata{},
		&VideoPerceptualHash{},
		&NearDuplicateDismissal{},
		&VideoEnhancementTask{},
		&MediaStream{},
		&Image{},
		&ImageDirectory{},
		&ImageTrashEntry{},
		&ImageAIDescription{},
		&ImageNearDuplicateDismissal{},
	}
}
